/**
 * Accelerators & Incubators Database
 * Organized by region and stage for smart recommendations
 */

export type Stage = 'pre-seed' | 'seed' | 'series-a' | 'series-b' | 'growth';

export interface Accelerator {
  id: string;
  name: string;
  type: 'accelerator' | 'incubator' | 'vc-studio' | 'corporate';
  regions: string[];          // country codes or region names
  stages: Stage[];
  sectors: string[];          // 'all' or specific sector keys
  equity: string;             // e.g. "7%" or "0%"
  funding: string;            // e.g. "$125K" or "Up to $500K"
  duration: string;           // e.g. "3 months"
  location: string;
  description: string;
  highlights: string[];
  applyUrl: string;
  deadline: string;           // "Rolling" or specific cycle
  tier: 1 | 2 | 3;           // 1 = top-tier global, 2 = strong regional, 3 = local/niche
  remote: boolean;
}

export const ACCELERATORS: Accelerator[] = [
  // ─── Tier 1 Global ────────────────────────────────────────────────────────
  {
    id: 'yc',
    name: 'Y Combinator',
    type: 'accelerator',
    regions: ['global'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '7%',
    funding: '$500K',
    duration: '3 months',
    location: 'San Francisco, CA (remote-friendly)',
    description: 'The world\'s most prestigious startup accelerator. Backed over 4,000 companies including Airbnb, Stripe, Dropbox, and Coinbase.',
    highlights: ['$500K standard deal', 'Access to YC alumni network (4,000+ companies)', 'Demo Day with top-tier VCs', 'Lifetime YC network access'],
    applyUrl: 'https://www.ycombinator.com/apply',
    deadline: 'Rolling (2 batches/year: Jan & July)',
    tier: 1,
    remote: true,
  },
  {
    id: 'techstars',
    name: 'Techstars',
    type: 'accelerator',
    regions: ['global'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '6%',
    funding: '$120K',
    duration: '3 months',
    location: 'Multiple cities globally',
    description: 'Global accelerator network with 50+ programs worldwide. Strong mentor network and corporate partnerships.',
    highlights: ['Mentor-driven program', '50+ global programs', 'Strong alumni network', 'Corporate partnership opportunities'],
    applyUrl: 'https://www.techstars.com/accelerators',
    deadline: 'Rolling (varies by program)',
    tier: 1,
    remote: false,
  },
  {
    id: '500startups',
    name: '500 Global',
    type: 'accelerator',
    regions: ['global'],
    stages: ['seed'],
    sectors: ['all'],
    equity: '6%',
    funding: '$150K',
    duration: '4 months',
    location: 'San Francisco, CA + global programs',
    description: 'Global venture fund and accelerator with a strong focus on emerging markets and diverse founders.',
    highlights: ['Strong MENA & Asia programs', 'Growth hacking focus', 'Global investor network', 'Post-program support'],
    applyUrl: 'https://500.co/accelerators',
    deadline: 'Rolling',
    tier: 1,
    remote: true,
  },
  {
    id: 'sequoia-arc',
    name: 'Sequoia Arc',
    type: 'accelerator',
    regions: ['global'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Investment on merit',
    duration: '8 weeks',
    location: 'Global (remote)',
    description: 'Sequoia Capital\'s founder program. No equity taken — pure value-add with access to Sequoia\'s global network.',
    highlights: ['No equity taken', 'Sequoia network access', 'Curated cohort of 15-20 companies', 'Direct path to Sequoia investment'],
    applyUrl: 'https://www.sequoiacap.com/arc',
    deadline: 'Rolling',
    tier: 1,
    remote: true,
  },
  {
    id: 'a16z-speedrun',
    name: 'a16z Speedrun',
    type: 'accelerator',
    regions: ['global'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Investment on merit',
    duration: '4 weeks',
    location: 'San Francisco, CA',
    description: 'Andreessen Horowitz\'s founder program focused on consumer and enterprise software.',
    highlights: ['a16z network access', 'No equity taken', 'Intensive 4-week format', 'Direct VC introductions'],
    applyUrl: 'https://a16z.com/speedrun',
    deadline: 'Rolling',
    tier: 1,
    remote: false,
  },

  // ─── MENA Region ──────────────────────────────────────────────────────────
  {
    id: 'flat6labs',
    name: 'Flat6Labs',
    type: 'accelerator',
    regions: ['SA', 'AE', 'EG', 'BH', 'TN', 'MA', 'JO', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '5-10%',
    funding: '$20K–$100K',
    duration: '4 months',
    location: 'Cairo, Riyadh, Abu Dhabi, Bahrain, Tunis, Casablanca, Amman',
    description: 'MENA\'s leading startup accelerator with programs across 7 cities. Strong local ecosystem connections.',
    highlights: ['MENA-focused network', 'Local market expertise', 'Government partnerships', 'Arabic-speaking support'],
    applyUrl: 'https://www.flat6labs.com/apply',
    deadline: 'Rolling (multiple cohorts/year)',
    tier: 2,
    remote: false,
  },
  {
    id: 'misk',
    name: 'Misk Accelerator',
    type: 'accelerator',
    regions: ['SA', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'SAR 300K (~$80K)',
    duration: '3 months',
    location: 'Riyadh, Saudi Arabia',
    description: 'Saudi Arabia\'s premier accelerator backed by Misk Foundation. Focuses on Vision 2030 aligned sectors.',
    highlights: ['No equity taken', 'Saudi Vision 2030 alignment', 'Government connections', 'Strong local VC network'],
    applyUrl: 'https://misk.org.sa/accelerator',
    deadline: 'Annual (Q1)',
    tier: 2,
    remote: false,
  },
  {
    id: 'sdaia-accelerator',
    name: 'SDAIA Accelerator',
    type: 'accelerator',
    regions: ['SA', 'mena'],
    stages: ['seed', 'series-a'],
    sectors: ['aiml', 'dataanalytics', 'cybersecurity'],
    equity: '0%',
    funding: 'Up to SAR 500K',
    duration: '3 months',
    location: 'Riyadh, Saudi Arabia',
    description: 'Saudi Data & AI Authority accelerator focused exclusively on AI, data, and smart city startups.',
    highlights: ['AI/Data focus', 'Government procurement opportunities', 'NEOM & smart city access', 'Regulatory fast-track'],
    applyUrl: 'https://sdaia.gov.sa',
    deadline: 'Annual',
    tier: 2,
    remote: false,
  },
  {
    id: 'dtec',
    name: 'DTEC (Dubai Technology Entrepreneur Campus)',
    type: 'incubator',
    regions: ['AE', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Office space + support',
    duration: 'Ongoing',
    location: 'Dubai Silicon Oasis, UAE',
    description: 'Dubai\'s largest tech startup hub offering co-working, incubation, and acceleration services.',
    highlights: ['Dubai Silicon Oasis license support', 'Visa assistance', 'Investor network', 'Free zone benefits'],
    applyUrl: 'https://dtec.ae',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'hub71',
    name: 'Hub71',
    type: 'incubator',
    regions: ['AE', 'mena'],
    stages: ['pre-seed', 'seed', 'series-a'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Up to $415K in incentives',
    duration: 'Ongoing',
    location: 'Abu Dhabi, UAE',
    description: 'Abu Dhabi\'s global tech ecosystem backed by Mubadala, Microsoft, and SoftBank. Offers housing, health insurance, and office subsidies.',
    highlights: ['$415K incentive package', 'Housing subsidy', 'Health insurance', 'Mubadala & SoftBank network'],
    applyUrl: 'https://hub71.com/apply',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'wamda',
    name: 'Wamda Capital',
    type: 'vc-studio',
    regions: ['AE', 'SA', 'JO', 'LB', 'mena'],
    stages: ['seed', 'series-a'],
    sectors: ['all'],
    equity: 'Varies',
    funding: '$500K–$5M',
    duration: 'Ongoing',
    location: 'Dubai, UAE',
    description: 'MENA-focused VC and ecosystem builder supporting tech entrepreneurs across the Arab world.',
    highlights: ['MENA market expertise', 'Cross-border expansion support', 'Strong LP network', 'Policy advocacy'],
    applyUrl: 'https://www.wamda.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'oqal',
    name: 'Oqal Angel Network',
    type: 'accelerator',
    regions: ['SA', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: 'Varies',
    funding: 'SAR 100K–1M',
    duration: 'Varies',
    location: 'Riyadh, Saudi Arabia',
    description: 'Saudi Arabia\'s largest angel investor network connecting startups with local HNW investors.',
    highlights: ['Largest Saudi angel network', 'Local investor connections', 'Sharia-compliant options', 'Government backing'],
    applyUrl: 'https://oqal.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },

  // ─── Europe ───────────────────────────────────────────────────────────────
  {
    id: 'seedcamp',
    name: 'Seedcamp',
    type: 'accelerator',
    regions: ['GB', 'DE', 'FR', 'NL', 'SE', 'europe'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '7%',
    funding: '€200K',
    duration: 'Ongoing',
    location: 'London, UK (pan-European)',
    description: 'Europe\'s leading pre-seed fund and accelerator. Backed Revolut, UiPath, and Wise.',
    highlights: ['Pan-European network', 'Strong fintech/deeptech focus', 'Long-term founder support', 'London HQ'],
    applyUrl: 'https://seedcamp.com/apply',
    deadline: 'Rolling',
    tier: 1,
    remote: true,
  },
  {
    id: 'station-f',
    name: 'Station F (Paris)',
    type: 'incubator',
    regions: ['FR', 'europe'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Office space + programs',
    duration: 'Ongoing',
    location: 'Paris, France',
    description: 'World\'s largest startup campus with 30+ programs including Facebook, Microsoft, and Ubisoft tracks.',
    highlights: ['World\'s largest startup campus', '30+ programs', 'Paris ecosystem access', 'Visa support for non-EU'],
    applyUrl: 'https://stationf.co/programs',
    deadline: 'Rolling',
    tier: 1,
    remote: false,
  },
  {
    id: 'startupwise-guys',
    name: 'Startup Wise Guys',
    type: 'accelerator',
    regions: ['EE', 'LV', 'LT', 'europe'],
    stages: ['pre-seed', 'seed'],
    sectors: ['saas', 'b2b', 'fintech'],
    equity: '8%',
    funding: '€65K',
    duration: '3 months',
    location: 'Tallinn, Estonia (pan-European)',
    description: 'Europe\'s top B2B SaaS accelerator with strong focus on Baltic and CEE startups.',
    highlights: ['B2B SaaS specialist', 'EU market entry support', 'Strong mentor network', 'e-Residency support'],
    applyUrl: 'https://startupwiseguys.com/apply',
    deadline: 'Rolling',
    tier: 2,
    remote: true,
  },

  // ─── Asia-Pacific ─────────────────────────────────────────────────────────
  {
    id: 'antler',
    name: 'Antler',
    type: 'vc-studio',
    regions: ['global', 'SG', 'IN', 'AU', 'NG', 'SE', 'NL', 'GB'],
    stages: ['pre-seed'],
    sectors: ['all'],
    equity: '10%',
    funding: '$200K–$400K',
    duration: '3 months',
    location: 'Singapore + 25 global cities',
    description: 'Global early-stage VC that builds companies from scratch. Matches co-founders and provides pre-seed funding.',
    highlights: ['Co-founder matching', '25+ global locations', 'Day-0 company building', 'Strong Asia-Pacific network'],
    applyUrl: 'https://www.antler.co/apply',
    deadline: 'Rolling',
    tier: 1,
    remote: false,
  },
  {
    id: 'plug-and-play',
    name: 'Plug and Play Tech Center',
    type: 'accelerator',
    regions: ['global', 'US', 'DE', 'JP', 'AE', 'SG'],
    stages: ['seed', 'series-a'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Corporate partnerships',
    duration: '3 months',
    location: 'Silicon Valley + 50 global locations',
    description: 'Corporate innovation platform connecting startups with Fortune 500 companies for pilots and investments.',
    highlights: ['No equity taken', '50+ global locations', 'Corporate pilot opportunities', 'Fortune 500 connections'],
    applyUrl: 'https://www.plugandplaytechcenter.com/apply',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },

  // ─── US Regional ──────────────────────────────────────────────────────────
  {
    id: 'mit-delta-v',
    name: 'MIT delta v',
    type: 'accelerator',
    regions: ['US'],
    stages: ['pre-seed', 'seed'],
    sectors: ['deeptech', 'biotech', 'aiml'],
    equity: '0%',
    funding: '$20K stipend',
    duration: '3 months',
    location: 'Cambridge, MA',
    description: 'MIT\'s flagship student/alumni accelerator. Strong focus on deep tech and science-based startups.',
    highlights: ['MIT network access', 'No equity taken', 'Deep tech focus', 'Strong research commercialization'],
    applyUrl: 'https://entrepreneurship.mit.edu/accelerator',
    deadline: 'Annual (Spring)',
    tier: 2,
    remote: false,
  },
  {
    id: 'nsvf',
    name: 'National Science Foundation I-Corps',
    type: 'accelerator',
    regions: ['US'],
    stages: ['pre-seed'],
    sectors: ['deeptech', 'biotech', 'cleantech'],
    equity: '0%',
    funding: '$50K grant',
    duration: '7 weeks',
    location: 'US (remote + in-person)',
    description: 'NSF program helping scientists and engineers commercialize research. $50K non-dilutive grant.',
    highlights: ['Non-dilutive $50K', 'Customer discovery focus', 'Research commercialization', 'NSF network'],
    applyUrl: 'https://www.nsf.gov/news/special_reports/i-corps',
    deadline: 'Rolling (cohorts)',
    tier: 2,
    remote: true,
  },

  // ─── Southeast Asia ────────────────────────────────────────────────────────
  {
    id: 'iterative',
    name: 'Iterative',
    type: 'accelerator',
    regions: ['SG', 'MY', 'ID', 'TH', 'VN', 'PH', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '10%',
    funding: '$150K',
    duration: '3 months',
    location: 'Singapore (remote-friendly)',
    description: 'Southeast Asia\'s YC-style accelerator. Fully remote, focused on B2B SaaS and marketplace startups across SEA.',
    highlights: ['SEA-focused YC model', 'Remote-first', 'Strong B2B SaaS track', 'Singapore ecosystem access'],
    applyUrl: 'https://iterative.vc/apply',
    deadline: 'Rolling (2 batches/year)',
    tier: 2,
    remote: true,
  },
  {
    id: 'surge',
    name: 'Surge by Sequoia',
    type: 'accelerator',
    regions: ['SG', 'IN', 'ID', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '1–2%',
    funding: '$1–2M',
    duration: '16 weeks',
    location: 'Singapore + India',
    description: 'Sequoia Capital India & SEA\'s rapid scale program. Invests $1-2M for 1-2% equity — one of the best deals in Asia.',
    highlights: ['Sequoia network', 'Minimal equity taken', 'India + SEA focus', 'Direct Sequoia investment path'],
    applyUrl: 'https://www.surgeahead.com/apply',
    deadline: 'Rolling (2 cohorts/year)',
    tier: 1,
    remote: false,
  },
  {
    id: 'entrepreneur-first-sg',
    name: 'Entrepreneur First (Singapore)',
    type: 'vc-studio',
    regions: ['SG', 'sea'],
    stages: ['pre-seed'],
    sectors: ['all'],
    equity: '10%',
    funding: '$80K',
    duration: '3 months',
    location: 'Singapore',
    description: 'Talent investor that recruits exceptional individuals and helps them find co-founders and build companies from scratch.',
    highlights: ['Co-founder matching', 'Individual-first model', 'Singapore tech hub', 'Global EF alumni network'],
    applyUrl: 'https://www.joinef.com/apply',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'gojek-xcelerate',
    name: 'GDP Venture / Gojek Xcelerate',
    type: 'corporate',
    regions: ['ID', 'sea'],
    stages: ['seed', 'series-a'],
    sectors: ['fintech', 'logistics', 'ecommerce'],
    equity: 'Varies',
    funding: 'Up to $500K',
    duration: '3 months',
    location: 'Jakarta, Indonesia',
    description: 'Gojek\'s corporate accelerator focused on Indonesian and SEA startups in fintech, logistics, and digital commerce.',
    highlights: ['Gojek ecosystem access', 'Indonesia market entry', 'Corporate pilot opportunities', 'SEA distribution'],
    applyUrl: 'https://www.gdpventure.com',
    deadline: 'Annual',
    tier: 2,
    remote: false,
  },
  {
    id: 'mavcap',
    name: 'MAVCAP (Malaysia)',
    type: 'vc-studio',
    regions: ['MY', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: 'Varies',
    funding: 'Up to $500K',
    duration: 'Ongoing',
    location: 'Kuala Lumpur, Malaysia',
    description: 'Malaysia\'s national venture capital firm. Invests in Malaysian and SEA tech startups with government backing.',
    highlights: ['Government-backed VC', 'Malaysia market access', 'MSC Malaysia status support', 'Regional expansion support'],
    applyUrl: 'https://www.mavcap.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'true-incube',
    name: 'True Incube (Thailand)',
    type: 'incubator',
    regions: ['TH', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '5–10%',
    funding: 'Up to $200K',
    duration: '6 months',
    location: 'Bangkok, Thailand',
    description: 'Thailand\'s leading startup incubator backed by True Corporation. Strong corporate partnership and telco ecosystem.',
    highlights: ['True Corporation backing', 'Thailand market access', 'Corporate partnerships', 'ASEAN expansion support'],
    applyUrl: 'https://trueincube.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'ideaspace',
    name: 'IdeaSpace (Philippines)',
    type: 'accelerator',
    regions: ['PH', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'PHP 1M (~$18K) + support',
    duration: '6 months',
    location: 'Manila, Philippines',
    description: 'Philippines\' leading non-equity accelerator backed by PLDT and Smart Communications. Strong telco and fintech focus.',
    highlights: ['No equity taken', 'PLDT/Smart backing', 'Philippines market access', 'Telco pilot opportunities'],
    applyUrl: 'https://ideaspace.ph',
    deadline: 'Annual',
    tier: 2,
    remote: false,
  },

  // ─── MENA (Expanded) ──────────────────────────────────────────────────────
  {
    id: 'startupbootcamp-dubai',
    name: 'Startupbootcamp Dubai',
    type: 'accelerator',
    regions: ['AE', 'mena'],
    stages: ['seed'],
    sectors: ['fintech', 'smart-city', 'logistics'],
    equity: '6%',
    funding: '€15K + perks worth €450K',
    duration: '3 months',
    location: 'Dubai, UAE',
    description: 'Global accelerator with a dedicated Dubai program focused on FinTech, Smart City, and logistics startups.',
    highlights: ['Dubai FinTech Summit access', 'DIFC ecosystem', 'Corporate mentor network', 'EU + MENA dual exposure'],
    applyUrl: 'https://www.startupbootcamp.org/accelerator/dubai-fintech',
    deadline: 'Annual (Q1)',
    tier: 2,
    remote: false,
  },
  {
    id: 'brinc',
    name: 'Brinc',
    type: 'accelerator',
    regions: ['AE', 'HK', 'IN', 'mena', 'sea'],
    stages: ['pre-seed', 'seed'],
    sectors: ['iot', 'hardware', 'cleantech', 'foodtech'],
    equity: '7%',
    funding: '$100K',
    duration: '3 months',
    location: 'Dubai + Hong Kong + India',
    description: 'Hardware and IoT-focused accelerator with strong presence in MENA and Asia. Specializes in physical product startups.',
    highlights: ['Hardware/IoT specialist', 'Manufacturing connections', 'MENA + Asia dual track', 'Prototyping support'],
    applyUrl: 'https://brinc.io/apply',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'wadi-makkah',
    name: 'Wadi Makkah Ventures',
    type: 'vc-studio',
    regions: ['SA', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['edtech', 'healthtech', 'islamic-fintech'],
    equity: 'Varies',
    funding: 'SAR 200K–2M',
    duration: 'Ongoing',
    location: 'Makkah & Riyadh, Saudi Arabia',
    description: 'Saudi VC focused on Islamic economy, edtech, and healthtech. Strong connections to Hajj/Umrah economy and OIC markets.',
    highlights: ['Islamic economy focus', 'OIC market access', 'Hajj/Umrah ecosystem', 'Sharia-compliant structure'],
    applyUrl: 'https://wadimakkah.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'tamkeen-bahrain',
    name: 'Tamkeen (Bahrain)',
    type: 'incubator',
    regions: ['BH', 'mena'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Up to BHD 50K (~$133K) grant',
    duration: 'Ongoing',
    location: 'Manama, Bahrain',
    description: 'Bahrain\'s national labor fund offering non-dilutive grants and support for tech startups. Strong fintech focus via Bahrain FinTech Bay.',
    highlights: ['Non-dilutive grants', 'Bahrain FinTech Bay access', 'CBB regulatory sandbox', 'Gulf market entry'],
    applyUrl: 'https://tamkeen.bh',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'oman-tech',
    name: 'Oman Technology Fund (OTF)',
    type: 'vc-studio',
    regions: ['OM', 'mena'],
    stages: ['seed', 'series-a'],
    sectors: ['all'],
    equity: 'Varies',
    funding: 'Up to $2M',
    duration: 'Ongoing',
    location: 'Muscat, Oman',
    description: 'Oman\'s sovereign tech fund investing in local and regional startups. Backed by the Omani government to diversify the economy.',
    highlights: ['Government-backed fund', 'Oman market access', 'GCC expansion support', 'Vision 2040 alignment'],
    applyUrl: 'https://www.otf.om',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'qstp',
    name: 'Qatar Science & Technology Park (QSTP)',
    type: 'incubator',
    regions: ['QA', 'mena'],
    stages: ['pre-seed', 'seed', 'series-a'],
    sectors: ['deeptech', 'aiml', 'cleantech', 'healthtech'],
    equity: '0%',
    funding: 'Up to $250K + lab access',
    duration: 'Ongoing',
    location: 'Doha, Qatar',
    description: 'Qatar Foundation\'s tech park offering world-class lab facilities, funding, and access to Qatar\'s sovereign wealth ecosystem.',
    highlights: ['Qatar Foundation backing', 'World-class R&D facilities', 'QIA network access', 'Tax-free environment'],
    applyUrl: 'https://qstp.org.qa',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },

  // ─── Africa (Expanded) ────────────────────────────────────────────────────
  {
    id: 'ycombinator-africa',
    name: 'Y Combinator (Africa Track)',
    type: 'accelerator',
    regions: ['NG', 'KE', 'ZA', 'GH', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '7%',
    funding: '$500K',
    duration: '3 months',
    location: 'San Francisco (remote-friendly)',
    description: 'YC actively recruits African founders. Strong alumni base in Nigeria, Kenya, and South Africa.',
    highlights: ['Growing African cohort', 'Remote-friendly', 'Flutterwave, Paystack alumni', 'Global network'],
    applyUrl: 'https://www.ycombinator.com/apply',
    deadline: 'Rolling',
    tier: 1,
    remote: true,
  },
  {
    id: 'cchub',
    name: 'Co-Creation Hub (CcHUB)',
    type: 'incubator',
    regions: ['NG', 'KE', 'RW', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: 'Varies',
    funding: 'Up to $250K',
    duration: 'Ongoing',
    location: 'Lagos, Nigeria + Nairobi, Kigali',
    description: 'Africa\'s leading tech innovation center. Backed Ubenwa, Lifebank, and 200+ African startups.',
    highlights: ['Africa market expertise', 'Pan-African network', 'Social impact focus', 'Strong media & fintech track'],
    applyUrl: 'https://cchubnigeria.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'ihub',
    name: 'iHub (Kenya)',
    type: 'incubator',
    regions: ['KE', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Workspace + support',
    duration: 'Ongoing',
    location: 'Nairobi, Kenya',
    description: 'Nairobi\'s iconic tech hub and incubator. Birthplace of M-Pesa-era startups. Strong fintech and agritech community.',
    highlights: ['Silicon Savannah hub', 'East Africa market access', 'Fintech & agritech focus', 'Investor network'],
    applyUrl: 'https://ihub.co.ke',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'giz-make-it',
    name: 'GIZ Make-IT in Africa',
    type: 'accelerator',
    regions: ['NG', 'KE', 'GH', 'SN', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['agritech', 'healthtech', 'cleantech', 'edtech'],
    equity: '0%',
    funding: 'Up to €50K grant',
    duration: '6 months',
    location: 'Pan-African (remote + in-person)',
    description: 'German development agency GIZ program supporting African digital entrepreneurs with non-dilutive grants and mentorship.',
    highlights: ['Non-dilutive grants', 'German development network', 'Impact-focused', 'Pan-African reach'],
    applyUrl: 'https://www.make-it.africa',
    deadline: 'Annual',
    tier: 2,
    remote: true,
  },
  {
    id: 'startupgrind-africa',
    name: 'Google for Startups Africa',
    type: 'accelerator',
    regions: ['NG', 'KE', 'ZA', 'GH', 'EG', 'africa'],
    stages: ['seed', 'series-a'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Up to $350K in Google Cloud credits + support',
    duration: '3 months',
    location: 'Remote (Africa-focused)',
    description: 'Google\'s accelerator for African startups. Provides equity-free support, Google Cloud credits, and access to Google\'s global network.',
    highlights: ['No equity taken', '$350K Google Cloud credits', 'Google mentor network', 'Global visibility'],
    applyUrl: 'https://startup.google.com/programs/accelerator/africa',
    deadline: 'Annual',
    tier: 1,
    remote: true,
  },
  {
    id: 'ventures-platform',
    name: 'Ventures Platform (Nigeria)',
    type: 'vc-studio',
    regions: ['NG', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: 'Varies',
    funding: '$25K–$500K',
    duration: 'Ongoing',
    location: 'Abuja & Lagos, Nigeria',
    description: 'Nigeria\'s leading early-stage VC. Backed Paystack, Cowrywise, and 80+ African startups. Strong fintech and consumer focus.',
    highlights: ['Paystack/Cowrywise alumni', 'Nigeria market expertise', 'Pan-African expansion', 'Strong VC follow-on'],
    applyUrl: 'https://venturesplatform.com',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'cape-innovation',
    name: 'Cape Innovation & Technology Initiative (CiTi)',
    type: 'incubator',
    regions: ['ZA', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: '0%',
    funding: 'Support + workspace',
    duration: 'Ongoing',
    location: 'Cape Town, South Africa',
    description: 'South Africa\'s oldest tech incubator. Hub for Cape Town\'s growing startup ecosystem with strong fintech and creative tech focus.',
    highlights: ['Cape Town tech hub', 'SEDA-accredited', 'Fintech & creative tech', 'African continent gateway'],
    applyUrl: 'https://citi.org.za',
    deadline: 'Rolling',
    tier: 2,
    remote: false,
  },
  {
    id: 'seedstars-africa',
    name: 'Seedstars Africa Ventures',
    type: 'vc-studio',
    regions: ['NG', 'KE', 'GH', 'SN', 'CI', 'africa'],
    stages: ['pre-seed', 'seed'],
    sectors: ['all'],
    equity: 'Varies',
    funding: '$500K–$2M',
    duration: 'Ongoing',
    location: 'Pan-African',
    description: 'Swiss-based VC focused on emerging markets with a dedicated Africa fund. Strong francophone Africa presence.',
    highlights: ['Francophone Africa focus', 'Swiss investor network', 'Pan-African portfolio', 'Impact + returns focus'],
    applyUrl: 'https://www.seedstars.com/ventures',
    deadline: 'Rolling',
    tier: 2,
    remote: true,
  },
];

// ─── Country to Region Mapping ─────────────────────────────────────────────────

export const COUNTRY_TO_REGION: Record<string, string[]> = {
  // MENA
  'Saudi Arabia': ['SA', 'mena'],
  'UAE': ['AE', 'mena'],
  'Jordan': ['JO', 'mena'],
  'Bahrain': ['BH', 'mena'],
  'Kuwait': ['KW', 'mena'],
  'Qatar': ['QA', 'mena'],
  'Oman': ['OM', 'mena'],
  'Lebanon': ['LB', 'mena'],
  'Morocco': ['MA', 'mena'],
  'Tunisia': ['TN', 'mena'],
  'Iraq': ['IQ', 'mena'],
  // Americas
  'United States': ['US'],
  'Canada': ['CA'],
  'Brazil': ['BR'],
  'Mexico': ['MX'],
  // Europe
  'United Kingdom': ['GB', 'europe'],
  'Germany': ['DE', 'europe'],
  'France': ['FR', 'europe'],
  'Netherlands': ['NL', 'europe'],
  'Sweden': ['SE', 'europe'],
  'Estonia': ['EE', 'europe'],
  'Spain': ['ES', 'europe'],
  'Italy': ['IT', 'europe'],
  // Asia-Pacific
  'Singapore': ['SG', 'sea'],
  'India': ['IN'],
  'Australia': ['AU'],
  'Japan': ['JP'],
  'South Korea': ['KR'],
  'Indonesia': ['ID', 'sea'],
  'Malaysia': ['MY', 'sea'],
  'Thailand': ['TH', 'sea'],
  'Vietnam': ['VN', 'sea'],
  'Philippines': ['PH', 'sea'],
  'Myanmar': ['MM', 'sea'],
  'Cambodia': ['KH', 'sea'],
  'Pakistan': ['PK'],
  'Bangladesh': ['BD'],
  'Sri Lanka': ['LK'],
  // Africa
  'Nigeria': ['NG', 'africa'],
  'Kenya': ['KE', 'africa'],
  'South Africa': ['ZA', 'africa'],
  'Ghana': ['GH', 'africa'],
  'Rwanda': ['RW', 'africa'],
  'Ethiopia': ['ET', 'africa'],
  'Tanzania': ['TZ', 'africa'],
  'Uganda': ['UG', 'africa'],
  'Senegal': ['SN', 'africa'],
  'Egypt': ['EG', 'mena', 'africa'],
  'Ivory Coast': ['CI', 'africa'],
  'Other': ['global'],
};

export const COUNTRIES = Object.keys(COUNTRY_TO_REGION).sort();

// ─── Recommendation Engine ─────────────────────────────────────────────────────

export function recommendAccelerators(
  stage: Stage,
  country: string,
  sector: string,
  limit = 8
): Accelerator[] {
  const regions = COUNTRY_TO_REGION[country] || ['global'];

  const scored = ACCELERATORS.map(acc => {
    let score = 0;

    // Stage match
    if (acc.stages.includes(stage)) score += 40;
    else if (
      (stage === 'seed' && acc.stages.includes('pre-seed')) ||
      (stage === 'series-a' && acc.stages.includes('seed'))
    ) score += 20;

    // Region match
    if (acc.regions.includes('global')) score += 15;
    regions.forEach(r => {
      if (acc.regions.includes(r)) score += r === 'global' ? 10 : 30;
    });

    // Sector match
    if (acc.sectors.includes('all')) score += 10;
    else if (acc.sectors.includes(sector)) score += 20;

    // Tier bonus
    score += (4 - acc.tier) * 5;

    return { acc, score };
  });

  return scored
    .filter(s => s.score > 20)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.acc);
}
