/**
 * Term Sheet Glossary & Red Flags
 * Plain-English explanations of 80+ VC term sheet terms
 */

export interface TermDefinition {
  term: string;
  arabicTerm?: string;
  category: 'economics' | 'control' | 'protection' | 'governance' | 'exit' | 'fundraising' | 'captable' | 'legal' | 'duediligence' | 'metrics' | 'mena';
  plain: string;
  detail: string;
  redFlag: boolean;
  redFlagReason?: string;
  founderTip?: string;
  example?: string;
}

export const TERM_SHEET_GLOSSARY: TermDefinition[] = [
  // ─── Economics ────────────────────────────────────────────────────────────
  {
    term: 'Pre-Money Valuation',
    category: 'economics',
    plain: 'What your company is worth BEFORE the investor puts in money.',
    detail: 'If an investor puts in $2M at a $8M pre-money valuation, the post-money valuation is $10M and the investor owns 20%. This is the number you negotiate hardest.',
    redFlag: false,
    founderTip: 'Always clarify whether a valuation is pre- or post-money. Some investors quote post-money to make the deal look bigger.',
    example: '$8M pre-money + $2M investment = $10M post-money, investor owns 20%',
  },
  {
    term: 'Post-Money Valuation',
    category: 'economics',
    plain: 'What your company is worth AFTER the investor puts in money.',
    detail: 'Post-money = Pre-money + Investment. Investors often quote post-money valuations because the number sounds larger. Make sure you know which one you\'re discussing.',
    redFlag: false,
    example: 'Pre-money $8M + $2M investment = Post-money $10M',
  },
  {
    term: 'Dilution',
    category: 'economics',
    plain: 'The reduction in your ownership percentage when new shares are issued.',
    detail: 'Every time you raise money or issue stock options, existing shareholders get diluted. If you own 100% and raise money at a 20% stake, you now own 80%. Over multiple rounds, founders typically end up owning 15-30% at IPO.',
    redFlag: false,
    founderTip: 'Model your dilution across all future rounds before agreeing to any single round. Use the dilution simulator in this tool.',
  },
  {
    term: 'Option Pool',
    category: 'economics',
    plain: 'A reserved block of shares set aside for future employee stock options.',
    detail: 'Investors often require a 10-20% option pool to be created BEFORE their investment, which dilutes founders (not investors). This is called the "option pool shuffle" and effectively lowers your pre-money valuation.',
    redFlag: true,
    redFlagReason: 'If the option pool is created pre-investment, it dilutes founders, not investors. Negotiate to create it post-investment or keep it smaller.',
    founderTip: 'Ask for the option pool to be created post-money, or negotiate a smaller pool (10% vs 20%).',
    example: 'A $10M pre-money with a 20% option pool created pre-investment effectively values the company at $8M for founders.',
  },
  {
    term: 'Liquidation Preference',
    category: 'economics',
    plain: 'Investors get paid back first in an exit before founders see any money.',
    detail: 'A 1x non-participating preference means investors get their money back first, then founders split the rest. A 2x preference means investors get 2x their money before founders get anything. Participating preferred means investors get their preference AND share in the remaining proceeds.',
    redFlag: true,
    redFlagReason: 'Participating preferred with a high multiple (2x+) can leave founders with nothing in a modest exit. Push for 1x non-participating.',
    founderTip: 'Always push for 1x non-participating liquidation preference. Anything above 1x or "participating" is founder-unfriendly.',
    example: 'Investor puts in $5M with 2x participating preferred. In a $15M exit, investor gets $10M first, then 30% of remaining $5M = $11.5M total. Founders split $3.5M.',
  },
  {
    term: 'Participating Preferred',
    category: 'economics',
    plain: 'Investors get their money back AND share in the remaining proceeds — they get paid twice.',
    detail: 'This is one of the most founder-unfriendly terms. After getting their liquidation preference, participating preferred investors also participate in the remaining proceeds as if they had converted to common stock.',
    redFlag: true,
    redFlagReason: 'Participating preferred is often called "double-dipping." It significantly reduces founder proceeds in exits below a certain threshold.',
    founderTip: 'Negotiate for non-participating preferred, or add a cap (e.g., 3x) after which it converts to common.',
  },
  {
    term: 'Anti-Dilution Protection',
    category: 'protection',
    plain: 'Protects investors if you raise money at a lower valuation in the future (a "down round").',
    detail: 'Full ratchet anti-dilution reprices all investor shares to the new lower price — very bad for founders. Weighted average anti-dilution is more common and fairer, adjusting the conversion price based on how many shares were sold at the lower price.',
    redFlag: true,
    redFlagReason: 'Full ratchet anti-dilution is extremely founder-unfriendly. Insist on broad-based weighted average instead.',
    founderTip: 'Only accept "broad-based weighted average" anti-dilution. Never accept "full ratchet."',
    example: 'You raised at $10/share. Next round is at $5/share. Full ratchet: all previous investor shares reprice to $5 (massive dilution for founders). Weighted average: partial adjustment based on volume.',
  },
  {
    term: 'Valuation Cap',
    category: 'economics',
    plain: 'The maximum valuation at which a SAFE or convertible note converts into equity.',
    detail: 'Used in SAFEs and convertible notes. If you raise a SAFE with a $5M cap and later raise a priced round at $20M, the SAFE holder converts at $5M — getting 4x more shares than new investors. This rewards early risk-takers.',
    redFlag: false,
    founderTip: 'Set your SAFE cap at a realistic future valuation. Too low and you over-dilute yourself; too high and early investors won\'t bite.',
  },
  {
    term: 'Discount Rate (SAFE/Note)',
    category: 'economics',
    plain: 'A reward for early investors — they convert at a lower price than new investors.',
    detail: 'A 20% discount means early investors convert their note into equity at 80% of the price new investors pay. This is separate from the valuation cap — investors usually get whichever gives them more shares.',
    redFlag: false,
    example: 'New investors pay $1/share. Note holder with 20% discount converts at $0.80/share.',
  },
  {
    term: 'SAFE (Simple Agreement for Future Equity)',
    category: 'economics',
    plain: 'A simple investment instrument where investors give you money now and get equity later when you raise a priced round.',
    detail: 'Created by Y Combinator. No interest, no maturity date, no debt. Converts to equity at the next priced round based on the cap and/or discount. Very founder-friendly for early rounds.',
    redFlag: false,
    founderTip: 'SAFEs are generally founder-friendly. Watch out for "post-money SAFEs" (YC\'s current standard) vs "pre-money SAFEs" — post-money SAFEs are more dilutive to founders.',
  },
  {
    term: 'Convertible Note',
    category: 'economics',
    plain: 'A loan that converts into equity at a future round, with interest.',
    detail: 'Unlike a SAFE, a convertible note is debt with an interest rate (typically 5-8%) and a maturity date. If you don\'t raise before the maturity date, the note holder can demand repayment. Less founder-friendly than a SAFE.',
    redFlag: false,
    founderTip: 'Prefer SAFEs over convertible notes. If you must use a note, negotiate a long maturity date (24+ months) and automatic conversion.',
  },
  {
    term: 'MFN (Most Favored Nation)',
    category: 'economics',
    plain: 'If you give better terms to a future SAFE investor, existing SAFE holders automatically get those better terms too.',
    detail: 'Common in pre-money SAFEs. Protects early investors from being disadvantaged if you later offer a lower cap or higher discount to someone else. Generally reasonable for early investors.',
    redFlag: false,
    founderTip: 'MFN clauses are standard in early SAFEs. They\'re fair to early investors who took the most risk.',
  },
  {
    term: 'Price Per Share',
    category: 'economics',
    plain: 'The cost of one share of stock in the current funding round.',
    detail: 'Calculated as pre-money valuation divided by fully diluted shares outstanding. This is the benchmark price for the round — options are typically priced at or below this.',
    redFlag: false,
    example: '$10M pre-money ÷ 10M shares = $1.00 per share',
  },
  {
    term: 'Fully Diluted Shares',
    category: 'economics',
    plain: 'The total number of shares if every option, warrant, and convertible security were exercised today.',
    detail: 'Includes: issued shares + option pool (granted and ungranted) + warrants + convertible notes/SAFEs. Valuation is always calculated on a fully diluted basis. This is the denominator that determines your ownership percentage.',
    redFlag: false,
    founderTip: 'Always calculate your ownership on a fully diluted basis, not just issued shares. The difference can be significant.',
  },

  // ─── Control ──────────────────────────────────────────────────────────────
  {
    term: 'Board Seat',
    category: 'control',
    plain: 'The investor gets a seat on your board of directors and votes on major company decisions.',
    detail: 'Board composition is critical. A typical early-stage board is 2 founders + 1 investor + 1 independent. Watch out for investors demanding majority board control — they could override founder decisions.',
    redFlag: true,
    redFlagReason: 'If investors get majority board control early, they can fire founders, block acquisitions, or force decisions against founder interests.',
    founderTip: 'Maintain board control in early rounds. Aim for 2 founder seats, 1 investor seat, and 1 neutral independent you choose.',
  },
  {
    term: 'Protective Provisions',
    category: 'control',
    plain: 'A list of actions the company cannot take without investor approval.',
    detail: 'Standard protective provisions include: selling the company, raising more money, changing the charter, issuing new shares. These are generally reasonable. Watch out for overly broad provisions that require investor approval for routine business decisions.',
    redFlag: false,
    founderTip: 'Standard protective provisions are fine. Push back on any that require investor approval for day-to-day operations.',
  },
  {
    term: 'Drag-Along Rights',
    category: 'control',
    plain: 'If a majority of shareholders want to sell the company, they can force all other shareholders to sell too.',
    detail: 'This prevents a minority shareholder from blocking an acquisition. Generally reasonable, but watch out for drag-along rights held by investors alone — they could force a sale you don\'t want.',
    redFlag: true,
    redFlagReason: 'If investors have drag-along rights without founder consent, they could force a sale at a price that benefits them (due to liquidation preference) but leaves founders with little.',
    founderTip: 'Require that drag-along can only be triggered with both founder and investor consent, or by a supermajority including common shareholders.',
  },
  {
    term: 'Tag-Along Rights (Co-Sale)',
    category: 'control',
    plain: 'If a founder sells shares, investors have the right to sell their shares on the same terms.',
    detail: 'Protects investors from being left behind if a founder exits. Generally reasonable and standard.',
    redFlag: false,
  },
  {
    term: 'Right of First Refusal (ROFR)',
    category: 'control',
    plain: 'Before selling shares to a third party, you must offer them to existing investors first.',
    detail: 'Standard and generally reasonable. Prevents outside parties from buying into the company without existing investor knowledge.',
    redFlag: false,
    founderTip: 'ROFR is standard. Make sure it has a reasonable time window (30 days) and doesn\'t apply to small transfers like gifts to family.',
  },
  {
    term: 'Pro-Rata Rights',
    category: 'control',
    plain: 'The right to invest in future rounds to maintain their ownership percentage.',
    detail: 'Investors with pro-rata rights can invest in your Series A, B, etc. to avoid dilution. This is generally good — it signals investor confidence. But it can complicate future rounds if many investors exercise pro-rata.',
    redFlag: false,
    founderTip: 'Pro-rata is standard and generally fine. Be careful about giving "super pro-rata" rights which allow investors to buy MORE than their pro-rata share.',
  },
  {
    term: 'Voting Rights',
    category: 'control',
    plain: 'Who gets to vote on major company decisions and how much weight each vote carries.',
    detail: 'Common shareholders (founders, employees) typically have 1 vote per share. Preferred shareholders (investors) may have additional voting rights. Dual-class share structures give founders 10x or more votes per share, preserving control.',
    redFlag: false,
    founderTip: 'Consider a dual-class share structure early if you want to maintain voting control long-term. Much harder to implement after Series A.',
  },
  {
    term: 'Founder Veto Rights',
    category: 'control',
    plain: 'Certain decisions require founder approval regardless of board vote.',
    detail: 'Rarely granted but very founder-friendly. Gives founders the ability to block specific actions like firing the CEO or selling the company below a certain price.',
    redFlag: false,
    founderTip: 'Try to negotiate founder veto rights on: replacing the CEO, selling the company below a threshold, and issuing shares that dilute founders below 20%.',
  },
  {
    term: 'Observer Rights',
    category: 'control',
    plain: 'The right to attend board meetings and receive board materials, but without voting power.',
    detail: 'Often given to smaller investors who don\'t get a full board seat. They can watch and advise but can\'t vote. Generally harmless, but too many observers can make board meetings unwieldy.',
    redFlag: false,
    founderTip: 'Observer rights are generally fine. Limit the number and ensure they can be revoked if the investor becomes adversarial.',
  },

  // ─── Protection ───────────────────────────────────────────────────────────
  {
    term: 'Down Round Protection',
    category: 'protection',
    plain: 'Special protections that kick in if you raise money at a lower valuation than the previous round.',
    detail: 'Down rounds trigger anti-dilution adjustments, can damage employee morale, and signal distress to the market. Some term sheets include specific provisions that activate in down rounds, like ratchets or additional board seats for investors.',
    redFlag: true,
    redFlagReason: 'Down round provisions can significantly dilute founders. Understand exactly what triggers and what the impact is before signing.',
  },
  {
    term: 'Warranty & Representations',
    category: 'protection',
    plain: 'Legal promises you make to investors about the state of your company.',
    detail: 'You\'re legally certifying that your financial statements are accurate, you own your IP, there are no undisclosed lawsuits, etc. If these turn out to be false, investors can sue for damages.',
    redFlag: false,
    founderTip: 'Be extremely thorough and honest in your representations. Undisclosed issues discovered post-investment can void the deal or lead to litigation.',
  },
  {
    term: 'Indemnification',
    category: 'protection',
    plain: 'The company agrees to cover legal costs if directors or officers are sued for company-related actions.',
    detail: 'Standard and necessary to attract good board members. Without indemnification, no experienced director would join your board. Usually backed by D&O (Directors & Officers) insurance.',
    redFlag: false,
    founderTip: 'Get D&O insurance as soon as you have outside board members. It\'s relatively cheap and protects everyone.',
  },
  {
    term: 'Material Adverse Change (MAC)',
    category: 'protection',
    plain: 'A clause that lets investors back out of a deal if something significantly bad happens to the company before closing.',
    detail: 'If between signing the term sheet and closing the deal, something major goes wrong (key customer lost, lawsuit filed, key employee leaves), investors may invoke MAC to walk away.',
    redFlag: false,
    founderTip: 'MAC clauses are standard. Make sure the definition is narrow and specific — broad MAC clauses give investors too much flexibility to exit.',
  },
  {
    term: 'Lock-Up Period',
    category: 'protection',
    plain: 'A period after an IPO during which insiders cannot sell their shares.',
    detail: 'Typically 180 days after IPO. Prevents a flood of insider selling that would crash the stock price. Standard and required by underwriters.',
    redFlag: false,
    founderTip: 'Lock-up periods are standard and non-negotiable in IPOs. Plan your personal liquidity needs accordingly.',
  },

  // ─── Governance ───────────────────────────────────────────────────────────
  {
    term: 'Vesting Schedule',
    category: 'governance',
    plain: 'Founders and employees earn their equity over time, not all at once.',
    detail: 'Standard is 4-year vesting with a 1-year cliff: you earn 25% after 1 year, then 1/48th per month for 3 more years. This protects the company if a co-founder leaves early.',
    redFlag: false,
    founderTip: 'Negotiate for acceleration on change of control (double-trigger acceleration) — if the company is acquired AND you\'re fired, your unvested shares vest immediately.',
    example: '4-year vest, 1-year cliff: nothing for 12 months, then 25% vests, then 2.08%/month for 36 more months.',
  },
  {
    term: 'Cliff',
    category: 'governance',
    plain: 'A minimum time you must stay before any equity vests.',
    detail: 'A 1-year cliff means if you leave before 12 months, you get nothing. After the cliff, vesting continues monthly. Protects the company from co-founders who leave early.',
    redFlag: false,
  },
  {
    term: 'Double-Trigger Acceleration',
    category: 'governance',
    plain: 'Your unvested shares vest immediately if the company is acquired AND you\'re fired.',
    detail: 'Two triggers must happen: (1) acquisition and (2) involuntary termination. This protects founders from being fired after an acquisition before their equity vests. Always negotiate for this.',
    redFlag: false,
    founderTip: 'Always ask for double-trigger acceleration. Single-trigger (just acquisition) is less common but even better for founders.',
  },
  {
    term: 'Information Rights',
    category: 'governance',
    plain: 'Investors\' right to receive regular financial reports from the company.',
    detail: 'Standard information rights include monthly/quarterly financials and annual audited statements. Reasonable and expected. Watch out for overly broad information rights that require sharing competitive information.',
    redFlag: false,
  },
  {
    term: 'Founder Buyback',
    category: 'governance',
    plain: 'The company\'s right to repurchase a departing founder\'s unvested shares.',
    detail: 'If a founder leaves before their shares are fully vested, the company can buy back the unvested portion at the original issue price (usually near zero). This is standard and protects remaining founders and investors.',
    redFlag: false,
    founderTip: 'Make sure buyback rights expire after vesting is complete. Also negotiate for the buyback price to be fair market value if you leave after significant time.',
  },
  {
    term: 'Non-Compete Clause',
    category: 'governance',
    plain: 'You agree not to start or join a competing company for a period after leaving.',
    detail: 'Enforceability varies dramatically by jurisdiction (California bans them; most other states enforce them). Typically 1-2 years. Can severely limit your options if the company fails.',
    redFlag: true,
    redFlagReason: 'Broad non-competes can trap you in an industry for years. Push for narrow scope (specific product category, not entire industry) and short duration (12 months max).',
    founderTip: 'If you\'re in California, non-competes are generally unenforceable. In other states, negotiate scope and duration carefully.',
  },
  {
    term: 'Non-Solicitation',
    category: 'governance',
    plain: 'You agree not to recruit the company\'s employees or customers after leaving.',
    detail: 'More enforceable than non-competes in most jurisdictions. Typically 12-24 months. Prevents founders from leaving and immediately poaching the team.',
    redFlag: false,
    founderTip: 'Non-solicitation is generally reasonable. Keep the duration to 12 months and ensure it only covers people you directly managed.',
  },

  // ─── Exit ─────────────────────────────────────────────────────────────────
  {
    term: 'IPO Ratchet',
    category: 'exit',
    plain: 'If the IPO price is below a certain level, investors get extra shares to compensate.',
    detail: 'Very founder-unfriendly. Essentially guarantees investors a minimum return at the expense of founders and employees.',
    redFlag: true,
    redFlagReason: 'IPO ratchets can massively dilute founders at the moment of IPO. Avoid entirely.',
    founderTip: 'Refuse IPO ratchets. They are rare but extremely harmful to founders.',
  },
  {
    term: 'Pay-to-Play',
    category: 'exit',
    plain: 'Investors who don\'t participate in future rounds lose some of their special rights.',
    detail: 'Actually founder-friendly! Investors who don\'t invest in future rounds convert their preferred shares to common, losing liquidation preferences and other protections. Incentivizes continued investor support.',
    redFlag: false,
    founderTip: 'Pay-to-play provisions are actually good for founders — they keep investors engaged and committed.',
  },
  {
    term: 'Redemption Rights',
    category: 'exit',
    plain: 'Investors can demand their money back after a certain period.',
    detail: 'Typically after 5-7 years, investors can demand redemption if there\'s been no exit. This creates pressure to sell or IPO. Can be catastrophic if the company is doing well but hasn\'t exited.',
    redFlag: true,
    redFlagReason: 'Redemption rights can force a premature sale or create financial distress. Push to remove entirely or extend the timeline significantly.',
    founderTip: 'Push to remove redemption rights entirely. If you must accept them, negotiate for 7+ years and require a supermajority vote to exercise.',
  },
  {
    term: 'No-Shop Clause',
    category: 'exit',
    plain: 'You agree not to talk to other investors while negotiating with this one.',
    detail: 'Standard in term sheets. Usually 30-60 days. Reasonable — investors don\'t want you shopping their term sheet to get a better deal.',
    redFlag: false,
    founderTip: 'No-shop clauses are standard. Keep the window short (30 days) and ensure it expires automatically.',
  },
  {
    term: 'Acquisition Approval',
    category: 'exit',
    plain: 'Investors must approve any acquisition of the company.',
    detail: 'Usually part of protective provisions. Investors want to ensure they\'re not sold out in a deal that doesn\'t meet their return expectations. Standard but can block founder-preferred exits.',
    redFlag: false,
    founderTip: 'Negotiate a minimum acquisition price threshold below which investor approval is not required — this gives you flexibility for acqui-hires or small exits.',
  },
  {
    term: 'Liquidation Waterfall',
    category: 'exit',
    plain: 'The order in which different shareholders get paid in an exit.',
    detail: 'Typically: (1) debt holders, (2) preferred shareholders with liquidation preferences, (3) participating preferred, (4) common shareholders. Understanding your position in the waterfall is critical to knowing what you\'ll actually receive in an exit.',
    redFlag: false,
    founderTip: 'Model your exit proceeds across different exit valuations before signing any term sheet. A $50M exit can leave founders with nothing if the waterfall is stacked against them.',
    example: 'In a $20M exit with $15M in preferred liquidation preferences, common shareholders (founders, employees) receive only $5M to split.',
  },

  // ─── Fundraising Mechanics ────────────────────────────────────────────────
  {
    term: 'Lead Investor',
    category: 'fundraising',
    plain: 'The main investor who sets the terms, leads due diligence, and usually takes the largest check.',
    detail: 'The lead investor negotiates the term sheet, does the most due diligence, and typically takes a board seat. Other investors follow the lead\'s terms. Having a strong lead investor makes closing the round much easier.',
    redFlag: false,
    founderTip: 'Spend 80% of your fundraising energy finding the right lead. Once you have a lead, the rest of the round often fills quickly.',
  },
  {
    term: 'Bridge Round',
    category: 'fundraising',
    plain: 'A small, quick funding round to keep the company running until a larger round closes.',
    detail: 'Usually done with existing investors via convertible notes or SAFEs. Buys 3-6 months of runway. Can signal distress if done too frequently, but is a normal part of startup financing.',
    redFlag: false,
    founderTip: 'Raise bridge rounds proactively, not desperately. Start bridge conversations when you have 4-6 months of runway, not 1-2.',
  },
  {
    term: 'Tranched Investment',
    category: 'fundraising',
    plain: 'Investment paid in installments tied to hitting specific milestones.',
    detail: 'Instead of receiving all the money upfront, you receive portions as you hit targets (e.g., $500K now, $500K when you reach 1,000 users). Reduces investor risk but creates pressure and uncertainty for founders.',
    redFlag: true,
    redFlagReason: 'Tranched investments give investors leverage to withhold capital if they disagree with your direction. Push for full investment upfront.',
    founderTip: 'Avoid tranched investments if possible. If unavoidable, ensure milestones are objective, measurable, and within your control.',
  },
  {
    term: 'Closing Conditions',
    category: 'fundraising',
    plain: 'Requirements that must be met before the investment money is actually transferred.',
    detail: 'Common closing conditions: legal due diligence completion, shareholder approval, regulatory filings, and execution of all investment documents. Delays in closing conditions can extend timelines significantly.',
    redFlag: false,
    founderTip: 'Start working on closing conditions immediately after signing the term sheet. Legal delays are the most common cause of deal slippage.',
  },
  {
    term: 'Side Letter',
    category: 'fundraising',
    plain: 'A private agreement between the company and a specific investor that gives them special terms not in the main documents.',
    detail: 'Side letters can grant MFN rights, special information rights, or other preferences. They\'re binding but not disclosed to other investors. Too many side letters create a complex, hard-to-manage cap table.',
    redFlag: true,
    redFlagReason: 'Side letters create hidden obligations that complicate future rounds. Future investors will discover them in due diligence and may demand equal treatment.',
    founderTip: 'Minimize side letters. If you must grant them, ensure they sunset after the next round or after a specific date.',
  },
  {
    term: 'Rolling Close',
    category: 'fundraising',
    plain: 'Accepting investors into the round as they commit, rather than waiting for everyone to sign at once.',
    detail: 'Common in angel rounds and seed rounds. Allows you to start using capital sooner. Each investor who closes is in at the same terms as the final round.',
    redFlag: false,
    founderTip: 'Rolling closes are efficient for seed rounds. Set a hard deadline to create urgency and prevent the round from dragging on indefinitely.',
  },
  {
    term: 'Syndicate',
    category: 'fundraising',
    plain: 'A group of investors who pool their money to invest together, often led by one experienced investor.',
    detail: 'Common on AngelList and similar platforms. The lead investor does the diligence and negotiates terms; other investors follow. Good way to fill a round quickly with smaller checks.',
    redFlag: false,
    founderTip: 'Syndicates are efficient but can create cap table complexity. Prefer a single SPV (Special Purpose Vehicle) over many individual investors.',
  },
  {
    term: 'SPV (Special Purpose Vehicle)',
    category: 'fundraising',
    plain: 'A single legal entity that holds multiple investors\' money, appearing as one investor on your cap table.',
    detail: 'Instead of 20 individual angel investors, an SPV consolidates them into one entity. This simplifies your cap table, reduces administrative burden, and makes future rounds cleaner.',
    redFlag: false,
    founderTip: 'Always prefer SPVs over individual investors for angel rounds. A clean cap table is highly valued by Series A investors.',
  },

  // ─── Cap Table ────────────────────────────────────────────────────────────
  {
    term: 'Cap Table (Capitalization Table)',
    category: 'captable',
    plain: 'A spreadsheet showing who owns what percentage of your company.',
    detail: 'Lists all shareholders, their share classes, number of shares, and ownership percentage. Includes founders, investors, employees with options, and any convertible securities. Investors will scrutinize this in due diligence.',
    redFlag: false,
    founderTip: 'Keep your cap table clean and up-to-date from day one. Use a proper tool (Carta, Pulley) rather than a spreadsheet once you have outside investors.',
  },
  {
    term: 'Common Stock',
    category: 'captable',
    plain: 'The basic shares held by founders and employees — last in line to get paid in an exit.',
    detail: 'Common stock has no special rights. In an exit, common shareholders get paid after all preferred shareholders have received their liquidation preferences. Founders and employees hold common stock.',
    redFlag: false,
  },
  {
    term: 'Preferred Stock',
    category: 'captable',
    plain: 'Special shares held by investors that come with extra rights and protections.',
    detail: 'Preferred shareholders get paid before common shareholders in an exit. They also typically have voting rights, information rights, and other protections. Each funding round creates a new series of preferred stock (Series A, B, C, etc.).',
    redFlag: false,
  },
  {
    term: 'Warrant',
    category: 'captable',
    plain: 'The right to buy shares at a fixed price in the future.',
    detail: 'Similar to options but typically issued to investors or advisors rather than employees. Warrants have an expiration date and a strike price. If the company\'s value exceeds the strike price, warrants are "in the money."',
    redFlag: false,
    founderTip: 'Track all warrants carefully on your cap table. Unexpected warrant exercises can surprise founders during fundraising.',
  },
  {
    term: 'Strike Price (Exercise Price)',
    category: 'captable',
    plain: 'The price at which an option or warrant holder can buy shares.',
    detail: 'For employee options, the strike price is set at fair market value (409A valuation) at the time of grant. If the company\'s value grows, employees can buy shares at the lower strike price and profit from the difference.',
    redFlag: false,
    example: 'Strike price $0.10/share. Current value $2.00/share. Employee exercises 10,000 options: pays $1,000, receives shares worth $20,000.',
  },
  {
    term: '409A Valuation',
    category: 'captable',
    plain: 'An independent appraisal of your company\'s common stock value, required for setting employee option prices.',
    detail: 'Required by the IRS before issuing employee stock options. Sets the "fair market value" of common stock. Must be updated every 12 months or after a significant event (new funding round, major revenue milestone). Common stock is typically valued at 25-33% of preferred stock price.',
    redFlag: false,
    founderTip: 'Get a 409A valuation before issuing any employee options. Issuing options without a valid 409A can result in significant tax penalties for employees.',
  },
  {
    term: 'Phantom Equity',
    category: 'captable',
    plain: 'A bonus that mimics equity upside without actually giving employees real shares.',
    detail: 'Employees receive cash bonuses tied to company value growth, without becoming actual shareholders. Common in jurisdictions where equity issuance is complex or in companies that want to avoid cap table complexity.',
    redFlag: false,
    founderTip: 'Phantom equity is useful in markets where equity issuance is legally complex. Be transparent with employees about the difference between phantom equity and real equity.',
  },

  // ─── Legal & Compliance ───────────────────────────────────────────────────
  {
    term: 'IP Assignment',
    category: 'legal',
    plain: 'Founders legally transfer ownership of all intellectual property they created to the company.',
    detail: 'Critical to do before raising any money. If a founder created IP before the company was formed, or on the side, it must be formally assigned to the company. Investors will not fund a company where IP ownership is unclear.',
    redFlag: false,
    founderTip: 'Execute IP assignment agreements for all founders on day one. Also ensure any IP created at a previous employer is clearly excluded.',
  },
  {
    term: 'Delaware C-Corp',
    category: 'legal',
    plain: 'The preferred legal structure for VC-backed startups in the US.',
    detail: 'Most US VCs require companies to be incorporated as Delaware C-Corps before investing. Delaware has the most developed corporate law, predictable courts, and flexible charter options. If you\'re incorporated elsewhere, you\'ll likely need to reincorporate.',
    redFlag: false,
    founderTip: 'Incorporate as a Delaware C-Corp from day one if you plan to raise VC funding. Reincorporating later is expensive and time-consuming.',
  },
  {
    term: 'Accredited Investor',
    category: 'legal',
    plain: 'An investor who meets minimum wealth or income thresholds set by the SEC, allowing them to invest in private companies.',
    detail: 'In the US, an accredited investor has $1M+ net worth (excluding primary residence) or $200K+ annual income ($300K with spouse). Most startup investments are restricted to accredited investors under Regulation D.',
    redFlag: false,
    founderTip: 'Verify investor accreditation before accepting any investment. Accepting money from non-accredited investors can create serious legal issues.',
  },
  {
    term: 'Regulation D (Reg D)',
    category: 'legal',
    plain: 'The SEC exemption that allows startups to raise money from accredited investors without registering as a public company.',
    detail: 'Most startup fundraising happens under Reg D Rule 506(b) or 506(c). 506(b) allows up to 35 non-accredited investors but no general solicitation. 506(c) allows general solicitation but requires all investors to be verified accredited.',
    redFlag: false,
    founderTip: 'File your Form D with the SEC within 15 days of your first sale. Failure to file is a violation even if the underlying offering is exempt.',
  },
  {
    term: 'Data Room',
    category: 'legal',
    plain: 'A secure online folder containing all the documents investors need to review during due diligence.',
    detail: 'Typically includes: financial statements, cap table, incorporation documents, IP assignments, customer contracts, employee agreements, and product demos. A well-organized data room signals professionalism and speeds up closing.',
    redFlag: false,
    founderTip: 'Build your data room before starting fundraising, not during. Use Notion, Google Drive, or Docsend. Organize it logically and ensure all documents are current.',
  },

  // ─── Due Diligence ────────────────────────────────────────────────────────
  {
    term: 'Due Diligence',
    category: 'duediligence',
    plain: 'The process investors use to verify everything you\'ve told them before wiring money.',
    detail: 'Covers financial, legal, technical, and commercial aspects of the business. Typically takes 2-8 weeks. Investors will check your financials, talk to customers, review contracts, verify IP ownership, and assess the team.',
    redFlag: false,
    founderTip: 'Be proactive in due diligence. Disclose issues early — investors always find them, and discovering problems late kills deals. Early disclosure shows integrity.',
  },
  {
    term: 'Reference Checks',
    category: 'duediligence',
    plain: 'Investors call people who know you to verify your character, skills, and track record.',
    detail: 'Investors will call your former colleagues, customers, and sometimes even people you didn\'t list as references. Be aware that your reputation precedes you — the startup world is small.',
    redFlag: false,
    founderTip: 'Prepare your references in advance. Brief them on your current company and what to emphasize. Also do reference checks on investors — call their portfolio founders.',
  },
  {
    term: 'Customer Discovery Call',
    category: 'duediligence',
    plain: 'Investors talk directly to your customers to verify your claims about product-market fit.',
    detail: 'One of the most important parts of due diligence. Investors want to hear from customers unprompted. If customers can\'t articulate your value proposition or wouldn\'t be upset if you shut down, that\'s a red flag.',
    redFlag: false,
    founderTip: 'Introduce investors to your best customers, but don\'t coach them. Authentic customer enthusiasm is your strongest fundraising asset.',
  },
  {
    term: 'Technical Due Diligence',
    category: 'duediligence',
    plain: 'An expert review of your technology, code quality, architecture, and technical team.',
    detail: 'Common for deep tech, AI, and developer tool companies. An independent technical expert reviews your codebase, architecture decisions, scalability, and security. Can surface hidden technical debt or IP issues.',
    redFlag: false,
    founderTip: 'Clean up your codebase and documentation before technical due diligence. Technical debt isn\'t disqualifying, but undisclosed critical vulnerabilities are.',
  },
  {
    term: 'Representations & Warranties',
    category: 'duediligence',
    plain: 'Legal statements you certify as true about your company at the time of investment.',
    detail: 'Cover areas like: accurate financial statements, no undisclosed litigation, valid IP ownership, no material omissions, compliance with laws. If any rep or warranty is false, investors can seek damages or rescind the investment.',
    redFlag: false,
    founderTip: 'Read every representation carefully before signing. If anything is not 100% accurate, disclose it in the disclosure schedule rather than signing a false warranty.',
  },

  // ─── Metrics & KPIs ────────────────────────────────────────────────────────────────────
  {
    term: 'ARR (Annual Recurring Revenue)',
    arabicTerm: 'الإيرادات السنوية المتكررة',
    category: 'metrics',
    plain: 'The annualised value of all active subscription contracts.',
    detail: 'ARR = MRR × 12. It is the single most important metric for SaaS companies. Investors use ARR to calculate revenue multiples (e.g., “we invest at 10x ARR”). Only include recurring revenue — exclude one-time fees and professional services.',
    redFlag: false,
    founderTip: 'Never inflate ARR by including one-time payments. Investors will find out during due diligence and it destroys trust.',
    example: 'MRR of $50,000 × 12 = ARR of $600,000',
  },
  {
    term: 'MRR (Monthly Recurring Revenue)',
    arabicTerm: 'الإيرادات الشهرية المتكررة',
    category: 'metrics',
    plain: 'The predictable monthly revenue from all active subscriptions.',
    detail: 'MRR is broken down into New MRR (from new customers), Expansion MRR (upsells), Contraction MRR (downgrades), and Churned MRR (cancellations). Net New MRR = New + Expansion − Contraction − Churned.',
    redFlag: false,
    example: 'New MRR $20K + Expansion $5K − Churn $3K = Net New MRR $22K',
  },
  {
    term: 'Churn Rate',
    arabicTerm: 'معدل التراجع',
    category: 'metrics',
    plain: 'The percentage of customers or revenue lost each month (or year).',
    detail: 'Monthly churn above 2–3% is a serious problem. Annual churn above 10–15% makes it very hard to grow. Negative net revenue churn (expansion > churn) is the holy grail — it means existing customers grow faster than you lose them.',
    redFlag: false,
    founderTip: 'Distinguish between logo churn (number of customers lost) and revenue churn (MRR lost). Revenue churn matters more to investors.',
    example: '100 customers, 5 cancel = 5% monthly logo churn',
  },
  {
    term: 'CAC (Customer Acquisition Cost)',
    arabicTerm: 'تكلفة اكتساب العميل',
    category: 'metrics',
    plain: 'The total cost to acquire one new paying customer.',
    detail: 'CAC = Total Sales & Marketing Spend ÷ New Customers Acquired in the same period. Includes salaries, ad spend, tools, and events. A healthy SaaS CAC Payback Period is under 12 months.',
    redFlag: false,
    founderTip: 'Track blended CAC (all channels) and paid CAC (paid channels only) separately. Investors want to see CAC trending down as you scale.',
    example: '$50,000 S&M spend ÷ 100 new customers = $500 CAC',
  },
  {
    term: 'LTV (Lifetime Value)',
    arabicTerm: 'القيمة العمرية للعميل',
    category: 'metrics',
    plain: 'The total revenue you expect to earn from a customer over their entire relationship with you.',
    detail: 'LTV = ARPU ÷ Monthly Churn Rate (for SaaS). A healthy LTV:CAC ratio is 3:1 or higher. Below 1:1 means you lose money on every customer.',
    redFlag: false,
    example: 'ARPU $100/month, 2% monthly churn → LTV = $100 ÷ 0.02 = $5,000',
  },
  {
    term: 'Burn Rate',
    arabicTerm: 'معدل الإنفاق',
    category: 'metrics',
    plain: 'How much cash your company spends each month.',
    detail: 'Gross burn = total monthly expenses. Net burn = expenses minus revenue. Investors focus on net burn. A high burn rate with slow revenue growth is a red flag. Rule of thumb: raise enough to cover 18–24 months of runway.',
    redFlag: false,
    founderTip: 'Know your net burn number at all times. Running out of cash is the #1 reason startups fail.',
    example: 'Monthly expenses $200K, revenue $50K → Net burn $150K/month',
  },
  {
    term: 'Runway',
    arabicTerm: 'مدة البقاء',
    category: 'metrics',
    plain: 'How many months until you run out of cash at your current burn rate.',
    detail: 'Runway = Cash in Bank ÷ Net Monthly Burn. You should always have at least 6 months of runway visible before starting a fundraise (12–18 months is better). Fundraising takes 3–6 months on average.',
    redFlag: false,
    founderTip: 'Start fundraising when you have 9–12 months of runway, not 3. Desperation is visible to investors and weakens your negotiating position.',
  },
  {
    term: 'Gross Margin',
    arabicTerm: 'هامش الربح الإجمالي',
    category: 'metrics',
    plain: 'Revenue minus the direct cost of delivering your product or service.',
    detail: 'Gross Margin % = (Revenue − COGS) ÷ Revenue. SaaS companies typically have 70–85% gross margins. Marketplace businesses 40–60%. Hardware 20–40%. High gross margins give you more money to invest in growth.',
    redFlag: false,
    example: 'Revenue $1M, COGS $200K → Gross Margin 80%',
  },
  {
    term: 'NPS (Net Promoter Score)',
    arabicTerm: 'معدل الترشيح',
    category: 'metrics',
    plain: 'A measure of how likely customers are to recommend your product (scale of −10 to 100).',
    detail: 'Customers scoring 9–10 are Promoters, 7–8 are Passives, 0–6 are Detractors. NPS = % Promoters − % Detractors. Above 50 is excellent. SaaS benchmarks: 30–50 is good, 50+ is great.',
    redFlag: false,
    founderTip: 'Include your NPS in investor decks if it’s above 40. Below 30, work on product before fundraising.',
  },
  {
    term: 'DAU / MAU Ratio',
    arabicTerm: 'نسبة المستخدمين اليوميين إلى الشهريين',
    category: 'metrics',
    plain: 'The ratio of daily active users to monthly active users — a measure of how "sticky" your product is.',
    detail: 'DAU/MAU above 20% is considered good engagement. WhatsApp and Facebook are above 50%. For B2B SaaS, weekly active users (WAU) is often more relevant than DAU.',
    redFlag: false,
    example: '10,000 MAU, 3,000 DAU → 30% DAU/MAU ratio',
  },
  {
    term: 'Rule of 40',
    arabicTerm: 'قاعدة الأربعين',
    category: 'metrics',
    plain: 'A SaaS health benchmark: your revenue growth rate + profit margin should equal or exceed 40%.',
    detail: 'Rule of 40 = ARR Growth Rate % + EBITDA Margin %. A score above 40 indicates a healthy balance of growth and profitability. Used by investors to evaluate SaaS companies at Series B and beyond.',
    redFlag: false,
    example: '80% ARR growth + (−40%) EBITDA margin = 40 → passes the Rule of 40',
  },
  {
    term: 'Magic Number',
    arabicTerm: 'الرقم السحري',
    category: 'metrics',
    plain: 'Measures how efficiently your sales & marketing spend generates new recurring revenue.',
    detail: 'Magic Number = Net New ARR in Quarter ÷ S&M Spend in Prior Quarter. Above 0.75 is good; above 1.0 is excellent. Below 0.5 means your go-to-market is inefficient.',
    redFlag: false,
    example: 'Net New ARR $500K, prior quarter S&M $600K → Magic Number = 0.83',
  },

  // ─── MENA-Specific ───────────────────────────────────────────────────────────────────────
  {
    term: 'Free Zone Entity',
    arabicTerm: 'كيان المنطقة الحرة',
    category: 'mena',
    plain: 'A company registered inside a UAE (or GCC) free zone, with 100% foreign ownership and tax exemptions.',
    detail: 'Free zones like DIFC, ADGM, DMCC, and RAKEZ allow 100% foreign ownership, 0% corporate tax (within the zone), and full profit repatriation. The trade-off: you cannot trade directly with the UAE mainland without a local distributor or a mainland license.',
    redFlag: false,
    founderTip: 'If your customers are primarily in the UAE mainland, consider a dual structure: free zone holding company + mainland branch.',
  },
  {
    term: 'DIFC (Dubai International Financial Centre)',
    arabicTerm: 'مركز دبي المالي الدولي',
    category: 'mena',
    plain: 'A leading financial free zone in Dubai with its own courts, laws, and regulatory framework based on English common law.',
    detail: 'DIFC is the preferred jurisdiction for VC funds, fintech companies, and startups seeking institutional investment. It has its own DIFC Courts (highly regarded), DFSA regulation for financial services, and is recognised by international investors.',
    redFlag: false,
    founderTip: 'If you plan to raise from international institutional investors or run a fintech, DIFC is the gold standard in the region.',
  },
  {
    term: 'ADGM (Abu Dhabi Global Market)',
    arabicTerm: 'سوق أبوظبي العالمي',
    category: 'mena',
    plain: 'Abu Dhabi’s international financial centre, similar to DIFC but based in Abu Dhabi.',
    detail: 'ADGM uses English common law, has its own courts, and is regulated by FSRA. It is increasingly popular for VC funds, family offices, and tech startups. Abu Dhabi’s sovereign wealth funds (ADIA, Mubadala) prefer ADGM-registered entities.',
    redFlag: false,
    founderTip: 'If your primary investors or customers are Abu Dhabi-based, ADGM may give you easier access to government and sovereign fund capital.',
  },
  {
    term: 'Wasta',
    arabicTerm: 'واسطة',
    category: 'mena',
    plain: 'Informal influence, connections, or social capital used to facilitate business or access decision-makers in the Arab world.',
    detail: 'Wasta is a real factor in MENA business. Relationships with the right family, government official, or investor can open doors that cold outreach cannot. It is not corruption — it is relationship capital. Building wasta takes time and genuine relationship investment.',
    redFlag: false,
    founderTip: 'Invest in community events, accelerators, and government programs to build legitimate wasta. Attend GITEX, Expand North Star, and local VC events.',
  },
  {
    term: 'Nitaqat',
    arabicTerm: 'نطاقات',
    category: 'mena',
    plain: 'Saudi Arabia’s workforce nationalisation quota system requiring companies to hire a minimum percentage of Saudi nationals.',
    detail: 'Nitaqat classifies companies into Platinum, Green, Yellow, and Red bands based on their Saudi national (Saudization) ratio. Companies in Red or Yellow bands face restrictions on hiring expats, renewing visas, and government contracts. Startups must plan for Nitaqat compliance from day one in Saudi Arabia.',
    redFlag: false,
    founderTip: 'Build your Saudi hiring plan early. Some roles are exempt for startups, but ignoring Nitaqat can block your ability to hire foreign talent.',
  },
  {
    term: 'Emiratisation (Nafis)',
    arabicTerm: 'توطين',
    category: 'mena',
    plain: 'UAE’s policy requiring private sector companies to hire a minimum percentage of UAE nationals.',
    detail: 'The Nafis programme provides wage subsidies for UAE nationals hired in the private sector. Companies with 50+ employees must meet Emiratisation quotas or pay a monthly contribution per unfilled quota position. Startups under 50 employees are generally exempt.',
    redFlag: false,
    founderTip: 'If you plan to scale to 50+ employees in the UAE, factor Emiratisation costs and timelines into your hiring plan.',
  },
  {
    term: 'Maktab (Virtual Office)',
    arabicTerm: 'مكتب افتراضي',
    category: 'mena',
    plain: 'A registered office address service that satisfies free zone or mainland licensing requirements without a physical office.',
    detail: 'Most free zones allow startups to register with a virtual office (flexi-desk) licence at a fraction of the cost of a physical office. This is common for early-stage startups. Some free zones require physical presence for certain licence types.',
    redFlag: false,
    founderTip: 'Start with a flexi-desk or virtual office licence to minimise overhead. Upgrade to a physical office when you have 5+ employees or need client-facing space.',
  },
  {
    term: 'Baladiya (Municipality Approval)',
    arabicTerm: 'بلدية',
    category: 'mena',
    plain: 'Municipal approval required for certain business activities in GCC countries, in addition to the commercial licence.',
    detail: 'Some business activities (food, healthcare, education, retail) require additional municipality (Baladiya) approvals on top of the standard commercial licence. This adds time and cost to the setup process. Always check activity-specific requirements before incorporating.',
    redFlag: false,
    founderTip: 'Map all required approvals before starting your incorporation. Some regulated sectors (fintech, health, education) require 3–5 separate licences.',
  },
  {
    term: 'Zakat',
    arabicTerm: 'زكاة',
    category: 'mena',
    plain: 'An Islamic tax on business wealth, applicable to Saudi-owned companies and Saudi shareholders in Saudi Arabia.',
    detail: 'Zakat is 2.5% of the zakatable base (broadly: net assets minus fixed assets and long-term investments). It applies to Saudi and GCC national shareholders’ share of the business. Foreign shareholders pay corporate income tax instead. In Saudi Arabia, Zakat is administered by ZATCA.',
    redFlag: false,
    founderTip: 'If you have Saudi national co-founders or investors, factor Zakat obligations into your financial model.',
  },
  {
    term: 'Shariah-Compliant Financing',
    arabicTerm: 'تمويل متوافق مع الشريعة',
    category: 'mena',
    plain: 'Financing structures that comply with Islamic law, which prohibits charging or paying interest (riba).',
    detail: 'Common Shariah-compliant structures include Murabaha (cost-plus financing), Ijara (leasing), Musharaka (partnership/equity), and Sukuk (Islamic bonds). Many GCC investors and family offices prefer or require Shariah-compliant structures. Equity investment is inherently Shariah-compliant; debt with interest is not.',
    redFlag: false,
    founderTip: 'If you are raising from GCC family offices or Islamic banks, be prepared to discuss Shariah compliance. Equity rounds are straightforward; debt instruments need structuring.',
  },
  {
    term: 'Hawala',
    arabicTerm: 'حوالة',
    category: 'mena',
    plain: 'An informal value transfer system widely used in the MENA region, based on trust and a network of brokers.',
    detail: 'Hawala is used for remittances and informal money transfers. It is legal in most GCC countries when licensed. For startups, it is relevant as a competitor or use case in fintech, and as a compliance risk if your platform inadvertently facilitates unlicensed transfers.',
    redFlag: false,
    founderTip: 'If you are building a fintech product in MENA, understand how Hawala networks operate — they are your informal competition and a regulatory compliance area.',
  },
  {
    term: 'Vision 2030 (Saudi Arabia)',
    arabicTerm: 'رؤية 2030',
    category: 'mena',
    plain: 'Saudi Arabia’s national transformation plan to diversify the economy away from oil by 2030.',
    detail: 'Vision 2030 has created massive opportunities for startups in tourism, entertainment, healthcare, education, fintech, and logistics. Government procurement, grants, and accelerator programs are heavily aligned with Vision 2030 sectors. Startups that align their pitch with Vision 2030 themes have an advantage in Saudi fundraising.',
    redFlag: false,
    founderTip: 'If you are pitching Saudi investors or government entities, explicitly map your startup to Vision 2030 pillars. It signals strategic alignment.',
  },
  {
    term: 'Monsha’at',
    arabicTerm: 'منشآت',
    category: 'mena',
    plain: 'Saudi Arabia’s General Authority for Small and Medium Enterprises — the primary government body supporting SMEs and startups.',
    detail: 'Monsha’at provides grants, subsidised loans, training programmes, and access to government procurement for Saudi SMEs and startups. It administers the Kafalah loan guarantee programme and partners with accelerators. Registration with Monsha’at is often a prerequisite for government support programmes.',
    redFlag: false,
    founderTip: 'Register your Saudi entity with Monsha’at early. It unlocks access to grants, loan guarantees, and government procurement opportunities.',
  },
  {
    term: 'Hub71 (Abu Dhabi)',
    arabicTerm: 'هب 71',
    category: 'mena',
    plain: 'Abu Dhabi’s flagship tech startup ecosystem, backed by Mubadala and ADQ, offering funding, office space, and market access.',
    detail: 'Hub71 provides equity-free incentives (office space, housing, health insurance) to accepted startups, plus access to Mubadala’s network and co-investment opportunities. It focuses on deep tech, fintech, and climate tech. Acceptance is competitive but the benefits are substantial.',
    redFlag: false,
    founderTip: 'Apply to Hub71 if you are targeting the Abu Dhabi market or seeking Mubadala-connected investors. The non-dilutive benefits alone are worth the application effort.',
  },
];

export const TERM_CATEGORIES = [
  { id: 'all', label: 'All Terms' },
  { id: 'economics', label: 'Economics' },
  { id: 'control', label: 'Control' },
  { id: 'protection', label: 'Protection' },
  { id: 'governance', label: 'Governance' },
  { id: 'exit', label: 'Exit' },
  { id: 'fundraising', label: 'Fundraising' },
  { id: 'captable', label: 'Cap Table' },
  { id: 'legal', label: 'Legal' },
  { id: 'duediligence', label: 'Due Diligence' },
  { id: 'metrics', label: 'Metrics & KPIs' },
  { id: 'mena', label: 'MENA-Specific' },
];
