CREATE TABLE `kyc_angel_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`displayName` varchar(256) NOT NULL,
	`title` varchar(256),
	`bio` text,
	`location` varchar(256),
	`regions` json,
	`stages` json,
	`sectors` json,
	`checkSizeMin` float,
	`checkSizeMax` float,
	`notableInvestments` json,
	`linkedinUrl` varchar(512),
	`twitterUrl` varchar(512),
	`angellistUrl` varchar(512),
	`isPublic` boolean NOT NULL DEFAULT true,
	`isVerified` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kyc_angel_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `kyc_angel_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `kyc_lawyer_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`displayName` varchar(256) NOT NULL,
	`firmName` varchar(256),
	`title` varchar(256),
	`bio` text,
	`location` varchar(256),
	`regions` json,
	`specializations` json,
	`languages` json,
	`offersFreeConsult` boolean NOT NULL DEFAULT false,
	`linkedinUrl` varchar(512),
	`websiteUrl` varchar(512),
	`contactEmail` varchar(320),
	`isPublic` boolean NOT NULL DEFAULT true,
	`isVerified` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kyc_lawyer_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `kyc_lawyer_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `kyc_startup_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(256) NOT NULL,
	`tagline` varchar(512),
	`description` text,
	`website` varchar(512),
	`sector` varchar(128),
	`stage` enum('idea','pre-seed','seed','series-a','series-b','growth') NOT NULL DEFAULT 'idea',
	`country` varchar(128),
	`city` varchar(128),
	`foundedYear` int,
	`teamSize` int,
	`targetRaise` float,
	`linkedinUrl` varchar(512),
	`twitterUrl` varchar(512),
	`isPublic` boolean NOT NULL DEFAULT true,
	`isVerified` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kyc_startup_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `kyc_startup_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `kyc_vc_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firmName` varchar(256) NOT NULL,
	`yourTitle` varchar(128),
	`description` text,
	`website` varchar(512),
	`hqCity` varchar(128),
	`hqCountry` varchar(128),
	`regions` json,
	`stages` json,
	`sectors` json,
	`checkSizeMin` float,
	`checkSizeMax` float,
	`aum` float,
	`portfolioCount` int,
	`notablePortfolio` json,
	`linkedinUrl` varchar(512),
	`twitterUrl` varchar(512),
	`applyUrl` varchar(512),
	`isPublic` boolean NOT NULL DEFAULT true,
	`isVerified` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kyc_vc_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `kyc_vc_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `userType` enum('startup','vc','angel','venture_lawyer','other') DEFAULT 'startup' NOT NULL;--> statement-breakpoint
ALTER TABLE `users` ADD `kycCompleted` boolean DEFAULT false NOT NULL;