ALTER TABLE `startup_profiles` ADD `instagramUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `facebookUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `tiktokUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `appStoreUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `playStoreUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `problem` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `solution` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `targetCustomer` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `competitiveAdvantage` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `businessModel` varchar(64);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `revenueModel` varchar(256);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `productStatus` enum('idea','prototype','mvp','beta','launched','scaling');--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `techStack` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `patents` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `keyRisks` text;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `mrr` float;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `numberOfCustomers` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `monthlyActiveUsers` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `churnRate` float;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `ltv` float;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `cac` float;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `npsScore` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `employeeCount` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `fullTimeCount` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `partTimeCount` int;--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `incorporationCountry` varchar(128);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `incorporationType` varchar(128);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `taxId` varchar(128);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `registrationNumber` varchar(128);--> statement-breakpoint
ALTER TABLE `startup_profiles` ADD `nextFundingDate` timestamp;