/**
 * Terms & Conditions content for Polaris Arabia
 * Last updated: March 2026
 * Compliant with: Saudi Arabia PDPL (Royal Decree M/19, 1443H), E-Commerce Law (Royal Decree M/126),
 * and Communications & Information Technology Commission (CITC) regulations.
 */

export const TERMS_LAST_UPDATED = 'March 22, 2026';
export const PRIVACY_LAST_UPDATED = 'March 22, 2026';
export const COMPANY_NAME = 'Polaris Arabia';
export const COMPANY_FULL_NAME = 'Polaris Arabia Technology Company';
export const COMPANY_EMAIL = 'legal@polarisarabia.com';
export const COMPANY_ADDRESS = 'Riyadh, Kingdom of Saudi Arabia';
export const GOVERNING_LAW = 'Kingdom of Saudi Arabia';

export interface LegalSection {
  id: string;
  title: string;
  content: string[];
}

export const TERMS_SECTIONS: LegalSection[] = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: [
      'By accessing or using the Polaris Arabia platform ("Platform"), including all tools, features, and services offered at polarisarabia.com, you ("User") agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, you must immediately discontinue use of the Platform.',
      'These Terms constitute a legally binding agreement between you and Polaris Arabia Technology Company ("Company", "we", "us", or "our"), a company registered in the Kingdom of Saudi Arabia.',
      'We reserve the right to modify these Terms at any time. Continued use of the Platform after any modification constitutes your acceptance of the updated Terms. We will notify registered users of material changes via email or in-app notification.',
    ],
  },
  {
    id: 'description',
    title: '2. Description of Services',
    content: [
      'Polaris Arabia provides an AI-powered startup toolkit ("Services") designed to assist founders and entrepreneurs with startup valuation, equity management, fundraising preparation, legal document generation, financial modeling, and related activities.',
      'The Platform includes tools such as: startup valuation calculators, cap table management (ZestEquity), ESOP plan management, co-founder equity split analysis, dilution simulation, fundraising readiness assessments, pitch deck evaluation, investor pipeline management, SAFE note and convertible note generation, NDA generation, term sheet analysis, runway optimization, and AI-powered advisory services.',
      'The Services are provided for informational and educational purposes only. Nothing on the Platform constitutes legal, financial, tax, or investment advice. Users should consult qualified professionals before making any legal, financial, or business decisions.',
    ],
  },
  {
    id: 'eligibility',
    title: '3. Eligibility and Account Registration',
    content: [
      'You must be at least 18 years of age to use the Platform. By using the Platform, you represent and warrant that you are at least 18 years old and have the legal capacity to enter into a binding agreement.',
      'To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete.',
      'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately at legal@polarisarabia.com of any unauthorized use of your account.',
      'We reserve the right to suspend or terminate accounts that violate these Terms, provide false information, or engage in fraudulent or abusive behavior.',
    ],
  },
  {
    id: 'license',
    title: '4. License and Intellectual Property',
    content: [
      'Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Platform for your personal or internal business purposes.',
      'All content, features, and functionality of the Platform — including but not limited to text, graphics, logos, icons, images, audio clips, data compilations, software, and the compilation thereof — are the exclusive property of Polaris Arabia or its licensors and are protected by Saudi intellectual property laws and international copyright conventions.',
      'You may not: (a) reproduce, distribute, modify, create derivative works of, publicly display, or exploit any portion of the Platform without our prior written consent; (b) reverse engineer, decompile, or disassemble any software component of the Platform; (c) use any automated means to access or scrape the Platform; or (d) remove any proprietary notices or labels on the Platform.',
      'Documents generated by the Platform (e.g., NDA templates, SAFE notes, term sheets) are provided as starting templates only. You retain ownership of content you input into the Platform. We do not claim ownership over your startup data, financial information, or generated documents.',
    ],
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use Policy',
    content: [
      'You agree to use the Platform only for lawful purposes and in accordance with these Terms. You agree not to use the Platform:',
      '(a) In any way that violates applicable Saudi laws, regulations, or international law, including but not limited to the Saudi Anti-Cybercrime Law (Royal Decree M/17), E-Commerce Law, and PDPL;',
      '(b) To transmit any unsolicited or unauthorized advertising or promotional material;',
      '(c) To impersonate any person or entity, or falsely state or misrepresent your affiliation with a person or entity;',
      '(d) To engage in any conduct that restricts or inhibits anyone\'s use or enjoyment of the Platform, or which may harm the Company or users of the Platform;',
      '(e) To upload or transmit viruses, malware, or any other malicious code;',
      '(f) To attempt to gain unauthorized access to any part of the Platform, other accounts, or computer systems connected to the Platform.',
    ],
  },
  {
    id: 'disclaimer',
    title: '6. Disclaimer of Warranties',
    content: [
      'THE PLATFORM AND SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.',
      'We do not warrant that: (a) the Platform will be uninterrupted, timely, secure, or error-free; (b) the results obtained from use of the Platform will be accurate or reliable; (c) any errors in the Platform will be corrected.',
      'Valuation outputs, financial projections, equity calculations, and legal document templates generated by the Platform are provided for illustrative and educational purposes only. They do not constitute professional advice and should not be relied upon as the sole basis for any business, legal, or financial decision.',
      'The Company expressly disclaims all liability for decisions made based on outputs generated by the Platform\'s AI tools, calculators, or document generators.',
    ],
  },
  {
    id: 'limitation',
    title: '7. Limitation of Liability',
    content: [
      'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE SAUDI LAW, IN NO EVENT SHALL POLARIS ARABIA, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE PLATFORM.',
      'Our total liability to you for any claims arising from or related to these Terms or the Platform shall not exceed the amount you paid us in the twelve (12) months preceding the claim, or SAR 500 if you have not made any payments.',
      'Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law.',
    ],
  },
  {
    id: 'indemnification',
    title: '8. Indemnification',
    content: [
      'You agree to defend, indemnify, and hold harmless Polaris Arabia and its licensors, service providers, employees, agents, officers, directors, and successors from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys\' fees) arising out of or relating to: (a) your violation of these Terms; (b) your use of the Platform; (c) your violation of any third-party rights; or (d) your violation of any applicable law or regulation.',
    ],
  },
  {
    id: 'termination',
    title: '9. Termination',
    content: [
      'We may terminate or suspend your access to the Platform immediately, without prior notice or liability, for any reason, including if you breach these Terms.',
      'Upon termination, your right to use the Platform will immediately cease. If you wish to terminate your account, you may do so by contacting us at legal@polarisarabia.com or through the account settings page.',
      'All provisions of these Terms which by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnity, and limitations of liability.',
      'Upon account deletion, we will delete your personal data in accordance with our Privacy Policy and applicable Saudi PDPL requirements, subject to any legal retention obligations.',
    ],
  },
  {
    id: 'governing-law',
    title: '10. Governing Law and Dispute Resolution',
    content: [
      'These Terms shall be governed by and construed in accordance with the laws of the Kingdom of Saudi Arabia, without regard to its conflict of law provisions.',
      'Any dispute arising from or relating to these Terms or the Platform shall first be subject to good-faith negotiation between the parties for a period of thirty (30) days.',
      'If the dispute cannot be resolved through negotiation, it shall be submitted to the competent courts of the Kingdom of Saudi Arabia, specifically the courts in Riyadh, which shall have exclusive jurisdiction.',
      'For consumer disputes, you may also contact the Saudi E-Commerce Dispute Resolution Center or the Ministry of Commerce\'s consumer protection channels.',
    ],
  },
  {
    id: 'ecommerce',
    title: '11. E-Commerce Law Compliance',
    content: [
      'In compliance with the Saudi E-Commerce Law (Royal Decree M/126, 1440H) and its Implementing Regulations, we disclose the following:',
      'Commercial Registration: Polaris Arabia Technology Company, registered in the Kingdom of Saudi Arabia.',
      'Contact Information: legal@polarisarabia.com | Riyadh, Kingdom of Saudi Arabia.',
      'Product/Service Description: AI-powered startup toolkit providing valuation, equity management, fundraising, and legal document tools for founders.',
      'Pricing: All pricing is displayed in Saudi Riyals (SAR) and is inclusive of applicable VAT where required. Free tier services are provided at no cost.',
      'Right of Return/Cancellation: For subscription services, you may cancel your subscription at any time. Refunds for prepaid subscription periods are subject to our refund policy available at legal@polarisarabia.com.',
    ],
  },
  {
    id: 'general',
    title: '12. General Provisions',
    content: [
      'Entire Agreement: These Terms, together with our Privacy Policy, constitute the entire agreement between you and Polaris Arabia regarding the Platform and supersede all prior agreements.',
      'Severability: If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions will continue in full force and effect.',
      'Waiver: Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.',
      'Assignment: You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights and obligations under these Terms without restriction.',
      'Contact: For any questions about these Terms, please contact us at legal@polarisarabia.com.',
    ],
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    id: 'introduction',
    title: '1. Introduction and Controller Identity',
    content: [
      'This Privacy Policy describes how Polaris Arabia Technology Company ("Polaris Arabia", "we", "us", or "our") collects, uses, stores, and protects your personal data when you use the Polaris Arabia platform at polarisarabia.com ("Platform").',
      'This Policy is issued in compliance with the Saudi Arabia Personal Data Protection Law (PDPL), Royal Decree M/19 dated 9/2/1443H (corresponding to September 16, 2021), and its Implementing Regulations, which became fully enforceable on September 14, 2024.',
      'Data Controller: Polaris Arabia Technology Company, Riyadh, Kingdom of Saudi Arabia. Contact: legal@polarisarabia.com.',
      'By using the Platform, you acknowledge that you have read and understood this Privacy Policy and consent to the collection and processing of your personal data as described herein.',
    ],
  },
  {
    id: 'data-collected',
    title: '2. Personal Data We Collect',
    content: [
      'We collect the following categories of personal data:',
      'Account Data: Name, email address, profile picture, and authentication credentials when you register for an account.',
      'Startup Profile Data: Company name, sector, funding stage, revenue figures, burn rate, team size, problem statement, and solution description that you voluntarily enter into the Platform.',
      'Cap Table Data: Founder names, equity percentages, share counts, ESOP grant details, and instrument data (SAFE notes, convertible notes) that you enter into ZestEquity and related tools.',
      'Usage Data: Pages visited, tools used, features accessed, session duration, browser type, operating system, IP address, and device identifiers collected automatically.',
      'Communication Data: Messages you send to us via email or support channels.',
      'We do not collect sensitive personal data as defined under Article 2 of the PDPL (e.g., health data, biometric data, religious beliefs, criminal records) unless explicitly required and separately consented to.',
    ],
  },
  {
    id: 'legal-basis',
    title: '3. Legal Basis for Processing (PDPL Article 6)',
    content: [
      'Under the Saudi PDPL, we process your personal data on the following legal bases:',
      'Contractual Necessity: Processing necessary to provide the Services you have requested, including account management, tool functionality, and data storage.',
      'Legitimate Interest: Processing for platform security, fraud prevention, service improvement, and analytics — where such interests are not overridden by your rights.',
      'Consent: For marketing communications, optional analytics, and any processing not covered by the above bases. You may withdraw consent at any time by contacting legal@polarisarabia.com.',
      'Legal Obligation: Processing required to comply with applicable Saudi laws and regulations, including tax, audit, and regulatory requirements.',
    ],
  },
  {
    id: 'data-use',
    title: '4. How We Use Your Personal Data',
    content: [
      'We use your personal data for the following purposes:',
      '(a) Providing and improving the Platform and its features;',
      '(b) Managing your account and authenticating your identity;',
      '(c) Personalizing your experience and pre-filling tool inputs with your startup profile data;',
      '(d) Sending transactional communications (account confirmations, security alerts);',
      '(e) Sending marketing communications about new features or products — only with your prior consent and with an easy opt-out mechanism in every communication;',
      '(f) Analyzing usage patterns to improve Platform performance and user experience;',
      '(g) Detecting, preventing, and responding to fraud, security incidents, and technical issues;',
      '(h) Complying with legal obligations under Saudi law.',
    ],
  },
  {
    id: 'data-sharing',
    title: '5. Data Sharing and Third-Party Disclosure',
    content: [
      'We do not sell, rent, or trade your personal data to third parties for their marketing purposes.',
      'We may share your personal data with:',
      'Service Providers: Third-party vendors who assist in operating the Platform (cloud hosting, database services, authentication providers, analytics). All service providers are contractually bound to process data only on our instructions and in compliance with applicable law.',
      'Legal Requirements: We may disclose your data when required by Saudi law, court order, or government authority, or when necessary to protect the rights, property, or safety of Polaris Arabia, our users, or the public.',
      'Business Transfers: In the event of a merger, acquisition, or sale of assets, your data may be transferred to the acquiring entity, subject to the same privacy protections.',
      'Cross-Border Transfers: If your data is transferred outside the Kingdom of Saudi Arabia, we ensure adequate protection through contractual safeguards in compliance with PDPL Article 29 and the Data Transfer Regulations issued by SDAIA.',
    ],
  },
  {
    id: 'data-retention',
    title: '6. Data Retention',
    content: [
      'We retain your personal data for as long as your account is active or as needed to provide Services. Specifically:',
      'Account data is retained for the duration of your account and deleted within 30 days of account deletion, unless longer retention is required by law.',
      'Startup profile and cap table data is retained as long as your account is active. You may delete this data at any time through the Platform settings.',
      'Usage and analytics data is retained for up to 24 months in aggregated or anonymized form.',
      'Legal and compliance records may be retained for up to 10 years as required by Saudi commercial and tax laws.',
      'Upon expiry of the retention period, data is securely deleted or anonymized in accordance with PDPL requirements.',
    ],
  },
  {
    id: 'data-rights',
    title: '7. Your Rights Under the Saudi PDPL',
    content: [
      'Under Articles 4-9 of the Saudi PDPL, you have the following rights regarding your personal data:',
      'Right to Be Informed: The right to know what personal data we collect, how we use it, and with whom we share it (fulfilled by this Privacy Policy).',
      'Right of Access: The right to request a copy of the personal data we hold about you.',
      'Right to Correction: The right to request correction of inaccurate or incomplete personal data.',
      'Right to Erasure: The right to request deletion of your personal data, subject to legal retention requirements.',
      'Right to Restriction: The right to request that we limit the processing of your personal data in certain circumstances.',
      'Right to Data Portability: The right to receive your personal data in a structured, commonly used format.',
      'Right to Object: The right to object to processing based on legitimate interest, including for direct marketing.',
      'To exercise any of these rights, please contact us at legal@polarisarabia.com. We will respond within 30 days as required by the PDPL. You may also file a complaint with the Saudi Data and Artificial Intelligence Authority (SDAIA) at sdaia.gov.sa.',
    ],
  },
  {
    id: 'security',
    title: '8. Data Security',
    content: [
      'We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, disclosure, alteration, or destruction, in compliance with PDPL Article 19.',
      'Security measures include: TLS/HTTPS encryption for all data in transit; encryption of sensitive data at rest; access controls and authentication requirements; regular security assessments; and employee training on data protection.',
      'In the event of a personal data breach that is likely to result in a risk to your rights, we will notify SDAIA within 72 hours of becoming aware of the breach, and notify affected individuals without undue delay, as required by PDPL Article 20.',
      'While we take reasonable steps to protect your data, no method of transmission over the internet or electronic storage is 100% secure. We cannot guarantee absolute security.',
    ],
  },
  {
    id: 'cookies',
    title: '9. Cookies and Tracking Technologies',
    content: [
      'We use cookies and similar tracking technologies to operate and improve the Platform. In compliance with the PDPL, we obtain your consent before placing non-essential cookies.',
      'Essential Cookies: Required for the Platform to function (session management, authentication). These cannot be disabled.',
      'Analytics Cookies: Used to understand how users interact with the Platform. These are only placed with your consent.',
      'We do not use third-party advertising cookies or sell your browsing data to advertisers.',
      'You can manage cookie preferences through your browser settings. Disabling essential cookies may affect Platform functionality.',
    ],
  },
  {
    id: 'minors',
    title: '10. Children\'s Privacy',
    content: [
      'The Platform is not directed to individuals under the age of 18. We do not knowingly collect personal data from minors.',
      'If we become aware that we have collected personal data from a person under 18 without verified parental consent, we will take steps to delete such data promptly.',
      'If you believe we have inadvertently collected data from a minor, please contact us at legal@polarisarabia.com.',
    ],
  },
  {
    id: 'changes',
    title: '11. Changes to This Privacy Policy',
    content: [
      'We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors.',
      'We will notify you of material changes by posting the new Policy on this page with an updated "Last Updated" date, and by sending an email notification to registered users at least 30 days before the changes take effect.',
      'Your continued use of the Platform after the effective date of the revised Policy constitutes your acceptance of the changes.',
    ],
  },
  {
    id: 'contact',
    title: '12. Contact and Complaints',
    content: [
      'For any questions, requests, or complaints regarding this Privacy Policy or our data practices, please contact our Data Protection Officer at:',
      'Email: legal@polarisarabia.com',
      'Address: Polaris Arabia Technology Company, Riyadh, Kingdom of Saudi Arabia',
      'We will acknowledge your request within 5 business days and respond fully within 30 days.',
      'If you are not satisfied with our response, you have the right to lodge a complaint with the Saudi Data and Artificial Intelligence Authority (SDAIA) at sdaia.gov.sa or by calling the unified number 920033678.',
    ],
  },
];
