/**
 * AI Due Diligence Checklist Tool
 * Generates customized due diligence checklists for startups
 */

import { useState } from 'react';
import { trpc } from '@/lib/trpc';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ClipboardList, AlertTriangle, CheckCircle2, Circle,
  ChevronDown, ChevronUp, Loader2, Shield
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { useLanguage } from '@/contexts/LanguageContext';
import { SECTORS, STARTUP_STAGES } from '@shared/dropdowns';

type DDItem = { item: string; status: string; notes: string; redFlag: boolean };
type DDCategory = { category: string; priority: string; items: DDItem[] };
type DDResult = {
  summary: string;
  overallRiskLevel: string;
  categories: DDCategory[];
  topRedFlags: string[];
  quickWins: string[];
};

export default function AIDueDiligence() {
  const { t, isRTL } = useLanguage();
  const [form, setForm] = useState({ companyName: '', sector: '', stage: 'Seed', description: '' });
  const [result, setResult] = useState<DDResult | null>(null);
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());
  const [expandedCats, setExpandedCats] = useState<Set<string>>(new Set());

  const mutation = trpc.ai.dueDiligence.useMutation({
    onSuccess: (data) => {
      setResult(data as DDResult);
      // Expand all categories by default
      const cats = new Set((data as DDResult).categories.map(c => c.category));
      setExpandedCats(cats);
      toast.success('Due diligence checklist generated!');
    },
    onError: (err) => toast.error('Failed: ' + err.message),
  });

  const toggleItem = (key: string) => {
    setCheckedItems(prev => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  };

  const toggleCat = (cat: string) => {
    setExpandedCats(prev => {
      const next = new Set(prev);
      next.has(cat) ? next.delete(cat) : next.add(cat);
      return next;
    });
  };

  const priorityColor = (p: string) => {
    if (p === 'Critical') return 'bg-red-100 text-red-700 border-red-200';
    if (p === 'High') return 'bg-amber-100 text-amber-700 border-amber-200';
    return 'bg-blue-100 text-blue-700 border-blue-200';
  };

  const riskColor = (r: string) => {
    if (r === 'High') return 'text-red-600 bg-red-50 border-red-200';
    if (r === 'Medium') return 'text-amber-600 bg-amber-50 border-amber-200';
    return 'text-green-600 bg-green-50 border-green-200';
  };

  const totalItems = result?.categories.reduce((sum, c) => sum + c.items.length, 0) ?? 0;
  const completedItems = checkedItems.size;
  const progress = totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0;

  return (
    <div className="flex flex-col h-full overflow-y-auto p-5 lg:p-6 max-w-4xl mx-auto w-full">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: 'oklch(0.45 0.18 160)' }}>
            <ClipboardList className="w-4.5 h-4.5 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-foreground" style={{ fontFamily: 'Playfair Display, serif' }}>
              AI Due Diligence Checklist
            </h1>
            <p className="text-xs text-muted-foreground">Stage-appropriate DD checklist generated by AI</p>
          </div>
        </div>
      </div>

      {/* Form */}
      {!result && (
        <form onSubmit={e => { e.preventDefault(); if (!form.companyName || !form.sector || !form.description) { toast.error('Fill all fields'); return; } mutation.mutate(form); }} className="space-y-4 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <Label className="text-xs font-semibold mb-1.5 block">Company Name *</Label>
              <Input value={form.companyName} onChange={e => setForm(f => ({ ...f, companyName: e.target.value }))} placeholder="e.g. Acme Inc." className="text-sm" />
            </div>
            <div>
              <Label className="text-xs font-semibold mb-1.5 block">Sector / Vertical *</Label>
              <Select value={form.sector} onValueChange={v => setForm(f => ({ ...f, sector: v }))}>
                <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Select sector…" /></SelectTrigger>
                <SelectContent className="max-h-64 overflow-y-auto">
                  {SECTORS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs font-semibold mb-1.5 block">Stage *</Label>
              <Select value={form.stage} onValueChange={v => setForm(f => ({ ...f, stage: v }))}>
                <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Select stage…" /></SelectTrigger>
                <SelectContent>
                  {STARTUP_STAGES.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          </div>
          <div>
            <Label className="text-xs font-semibold mb-1.5 block">Company Description *</Label>
            <Textarea value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="What does the company do, what's the business model, who are the customers?" className="text-sm min-h-[90px] resize-none" />
          </div>
          <Button type="submit" disabled={mutation.isPending} className="w-full h-11 text-sm font-semibold" style={{ background: 'oklch(0.45 0.18 160)', color: 'white' }}>
            {mutation.isPending ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating checklist…</> : <><ClipboardList className="w-4 h-4 mr-2" /> Generate Due Diligence Checklist</>}
          </Button>
        </form>
      )}

      {/* Results */}
      <AnimatePresence>
        {result && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
            {/* Header row */}
            <div className="flex items-center justify-between">
              <h2 className="text-base font-bold text-foreground" style={{ fontFamily: 'Playfair Display, serif' }}>Due Diligence Checklist</h2>
              <Button variant="outline" size="sm" onClick={() => { setResult(null); setCheckedItems(new Set()); }} className="text-xs">New Checklist</Button>
            </div>

            {/* Summary + risk */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div className="md:col-span-2 p-4 rounded-xl border border-border bg-card">
                <p className="text-sm text-foreground leading-relaxed">{result.summary}</p>
              </div>
              <div className={`p-4 rounded-xl border flex flex-col items-center justify-center ${riskColor(result.overallRiskLevel)}`}>
                <Shield className="w-6 h-6 mb-1" />
                <div className="text-xs font-bold uppercase tracking-widest">Risk Level</div>
                <div className="text-lg font-black">{result.overallRiskLevel}</div>
              </div>
            </div>

            {/* Progress */}
            <div className="p-3 rounded-xl border border-border bg-card">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-foreground">Progress</span>
                <span className="text-xs text-muted-foreground">{completedItems}/{totalItems} items</span>
              </div>
              <div className="h-2 bg-secondary rounded-full overflow-hidden">
                <div className="h-full bg-green-500 rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
              </div>
              <div className="text-right text-xs text-muted-foreground mt-1">{progress}% complete</div>
            </div>

            {/* Red flags */}
            {result.topRedFlags.length > 0 && (
              <div className="p-4 rounded-xl border border-red-200 bg-red-50">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="w-4 h-4 text-red-600" />
                  <span className="text-xs font-bold text-red-700">Top Red Flags to Investigate</span>
                </div>
                <ul className="space-y-1">
                  {result.topRedFlags.map((f, i) => <li key={i} className="text-xs text-red-700 flex gap-2"><span className="shrink-0">⚠</span>{f}</li>)}
                </ul>
              </div>
            )}

            {/* Quick wins */}
            {result.quickWins.length > 0 && (
              <div className="p-4 rounded-xl border border-green-200 bg-green-50">
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle2 className="w-4 h-4 text-green-600" />
                  <span className="text-xs font-bold text-green-700">Quick Positive Signals</span>
                </div>
                <ul className="space-y-1">
                  {result.quickWins.map((w, i) => <li key={i} className="text-xs text-green-700 flex gap-2"><span className="shrink-0">✓</span>{w}</li>)}
                </ul>
              </div>
            )}

            {/* Categories */}
            {result.categories.map((cat) => (
              <div key={cat.category} className="border border-border rounded-xl overflow-hidden">
                <button
                  onClick={() => toggleCat(cat.category)}
                  className="w-full flex items-center justify-between px-4 py-3 bg-card hover:bg-secondary/30 transition-colors"
                >
                  <div className="flex items-center gap-2.5">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${priorityColor(cat.priority)}`}>{cat.priority}</span>
                    <span className="text-sm font-semibold text-foreground">{cat.category}</span>
                    <span className="text-xs text-muted-foreground">({cat.items.filter(i => checkedItems.has(`${cat.category}-${i.item}`)).length}/{cat.items.length})</span>
                  </div>
                  {expandedCats.has(cat.category) ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
                </button>
                <AnimatePresence>
                  {expandedCats.has(cat.category) && (
                    <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">
                      <div className="border-t border-border divide-y divide-border">
                        {cat.items.map((item) => {
                          const key = `${cat.category}-${item.item}`;
                          const checked = checkedItems.has(key);
                          return (
                            <div key={key} className={`flex gap-3 px-4 py-3 cursor-pointer hover:bg-secondary/20 transition-colors ${checked ? 'opacity-60' : ''}`} onClick={() => toggleItem(key)}>
                              <div className="shrink-0 mt-0.5">
                                {checked ? <CheckCircle2 className="w-4 h-4 text-green-500" /> : <Circle className="w-4 h-4 text-muted-foreground" />}
                              </div>
                              <div className="flex-1 min-w-0">
                                <div className="flex items-start gap-2">
                                  <span className={`text-xs font-medium ${checked ? 'line-through text-muted-foreground' : 'text-foreground'}`}>{item.item}</span>
                                  {item.redFlag && <Badge variant="destructive" className="text-[9px] shrink-0">Red Flag</Badge>}
                                </div>
                                <p className="text-[11px] text-muted-foreground mt-0.5">{item.notes}</p>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
